### ISSUE TITLE
User agent by client hints

### ISSUE THREAD

**Issue by NF075** [uazo/bromite-buildtools#11]
Real  User agent is not disabled by javascript clients hints. Only disabled by headers client hints. 
For me i can see my device model and Android version.
SAMSUNG SM-G960U
Android 12.
Etc, by javascript user agent client hints.
At least if possible spoof user agent to bromite : 
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.0.0 Mobile Safari/537.36
If can't completely disabled by javascript client hints. 

See by yourself. 
Test page:

https://browserleaks.com/client-hints

Thanks. :)

**Comment by uazo** [comment]
sorry, only seen now.
you have to use the official repo for problems. thank you.
