### ISSUE TITLE
Build and maintain the webview

### ISSUE THREAD

**Issue by imagecreation** [uazo/bromite-buildtools#110]
Hello, thanks for a great work!
Will you build android webview apks?

**Comment by uazo** [comment]
no, I haven't decided yet.
let me understand the motivation though, why do you think a webview build is also necessary?
That is, what goal are you setting for yourselves?

**Comment by imagecreation** [comment]
Well, some apps are using webview: browsers etc. And I tested - there are such fingerprints as getClientRects(), maybe more, which are same for each app.
It will improve privacy overall I guess

**Comment by uazo** [comment]
> Well, some apps are using webview

sure! But which ones specifically?
If I could change the behavior of apps like facebook by including more privacy then that would be interesting, but facebook uses its own webview, so...
which apps would be affected in your opinion?

**Comment by imagecreation** [comment]
Yes, these are the ones I actively use:
https://github.com/duckduckgo/Android
https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/
https://github.com/jobobby04/TachiyomiSY
https://github.com/TrixiEther/DashchanFork
Afaik they all use internal android webview.

**Comment by marcdw1289** [comment]
Webview is a very important component that needs to be kept updated. I also make use of webview-based browsers (like Privacy Browser, Fulguris, Midori, FOSS Browser, etc) plus so many apps need it.

Having yet another webview would not matter unless it was supported by the ROM in use. For custom ROMs it has historically been `com.android.webview`.

When Bromite used the same package name it was generally just a matter of flashing it to replace the old.
Then Bromite changed the package name and ended that. All was not lost as there were Magisk and Xposed modules to handle it. As well as flashing/installing an overlay file,  if not using the above.

With Bromite development stalled folks still needed an up to date webview. That would be Mulch (from DivestOS). Again, not usable unless there is ROM support. Luckily the community jumps in and now Mulch Webview is on all of my devices going down to Oreo.

So even if there were an "Uazo WebView" it would not be usable out of the box. Unless maybe if it adopted the old package name (and even then. `com.android.webview` isn't/wasn't supported on most OEM Stock firmware).
Probably a good reason why csagan didn't entertain webview issues/reports. :-)

**Comment by marcdw1289** [comment]
Webview is a very important component that needs to be kept updated. I also make use of webview-based browsers (like Privacy Browser, Fulguris, Midori, FOSS Browser, etc) plus so many apps need it.

Having yet another webview would not matter unless it was supported by the ROM in use. For custom ROMs it has historically been `com.android.webview`.

When Bromite used the same package name it was generally just a matter of flashing it to replace the old.
Then Bromite changed the package name and ended that. All was not lost as there were Magisk and Xposed modules to handle it. As well as flashing/installing an overlay file,  if not using the above.

With Bromite development stalled folks still needed an up to date webview. That would be Mulch (from DivestOS). Again, not usable unless there is ROM support. Luckily the community jumps in and now Mulch Webview is on all of my devices going down to Oreo.

So even if there were an "Uazo WebView" it would not be usable out of the box. Unless maybe if it adopted the old package name (and even then. `com.android.webview` isn't/wasn't supported on most OEM Stock firmware).
Probably a good reason why csagan didn't entertain webview issues/reports. :-)

**Comment by marcdw1289** [comment]
Almost forgot, here is a method of getting Mulch WebView working on most ROMs.

[GitHub - A4Alpha/mulch-webview-overlay: Easily install the security-hardened Mulch SystemWebView from DivestOS](https://github.com/A4Alpha/mulch-webview-overlay)

**Comment by uazo** [comment]
> folks still needed an up to date webview. 

That's what I don't understand, why?

the webview is used by an application that has potential access to everything, why do I need to restrict only the webview when information can be passed in a thousand other ways?

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
