### ISSUE TITLE
Partitioned cookies don't work on non-secure sites

### ISSUE THREAD

**Issue by Arien02** [uazo/bromite-buildtools#113]
Hi.

I realized that can't login to pihole admin interface anymore.

Everytime I enter the correct passwd, it refresh the login screen again, endless loop.
If I enter incorrect passwd, pihole shows the wrong attempt.

Using currently v.110.0.5563.115
Works with Firefox or Chrome current versions.

Any suggestion?

**Comment by uazo** [comment]
thanks for the report.
unfortunately it also happens to one of my applications, so I think I have a test case available.

> Any suggestion?

Unfortunately, nothing so far.

**Comment by eskimododo** [comment]
I would like to report that I'm having the exact same issue trying to log into openmediavault server admin interface.

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/6c97952cbcf13e1dc6142d81eb2748369ba9ff75

**Comment by uazo** [comment]
@Arien02 @eskimododo can you try the latest version?

**Comment by Arien02** [comment]
Hey! It works! Thank you very much.

**Comment by eskimododo** [comment]
I can confirm it works too on the latest build.. thanks!
