### ISSUE TITLE
Secure DNS

### ISSUE THREAD

**Issue by sankhababu** [uazo/bromite-buildtools#119]
Not an issue, needs opinion about - 

Sorry to bother you again, Uazo.

I've two specific quarries which needs expert's opinion. 
If you please...

1) I'm using Private DNS in my android phone to avail that DNS, systemwide for every app.
In this situation, should I completely disable 'Use secure DNS' in the privacy setting of your Bromite build ? Or just enable 'Use your current service provider' option ?

2) Downloading new release from GitHub repo, often stops in the middle, due to unsteady network. Have to start from the beginning. Even enabling 'Parallel download' flag, resume capacity of chrome is very bad.
So I use FDM (free download manager) from Play store. I've found no trackers or loggers on testing with 'App Manager' (F-droid) and 'Warden' (IzzyOnDroid). 
BUT the latest version of FDM available, now NOT open source anymore. 
Is it still privacy-friendly ?
What is your opinion ?

Regards 🙏

**Comment by sankhababu** [comment]
In android 12 there is an option to set Private DNS of your choice, instead of using ISP's default one.
It's DNS over TLS. 
I use Adguard DNS for that, pasting tls://dns.adguard-dns.com in mobile's Private DNS setting. 
Details here -
https://adguard-dns.io/en/publi c-dns.html

**Comment by sankhababu** [comment]
> > Or just enable 'Use your current service provider' option ?
> 
> that option uses the system dns.
> 
> > I'm using Private DNS in my android phone
> 
> I don't know that application and how it works. is a local dns server? put the repo.
> 
> > So I use FDM (free download manager) from Play store
> 
> as above, I don't even know that application.
> 
> > Is it still privacy-friendly ? What is your opinion ?
> 
> you should check the privacy policy of that application, they have to indicate what data they take and how they use it.
> 
> > which needs expert's opinion.
> 
> as you can see, but I'm not!

You are so polite. 😊

**Comment by uazo** [comment]
>  I'm using Private DNS in my android phone

ah, I thought it was something else.

> you should check the privacy policy of that application

their privacy policy https://adguard.com/en/privacy/home.html

I am closing this issue because I do not understand how I can help you.
