### ISSUE TITLE
Always show context menu in links

### ISSUE THREAD

**Issue by JimW1at** [uazo/bromite-buildtools#121]
Can there be a way to change tap behaviour in the browser.

Single tap gesture changes to Long tap.

Long tap gesture changes to Single tap.

I want this for accessibility purpose.

Thanks for the app.

**Comment by uazo** [comment]
> Single tap gesture changes to Long tap.
> Long tap gesture changes to Single tap.

it does not look like it, but the solution you are proposing is easy to write but complex to implement!

> I want this for accessibility purpose.

let me understand the need

**Comment by JimW1at** [comment]
> let me understand the need

There is difficulty in long press and hold to bring the context menu on links, so i want this context menu to appear when i tap on the link instead of long press.

**Comment by uazo** [comment]
> so i want this context menu to appear when i tap on the link instead of long press.

OK, it's simpler this way. I would try this in a first phase.
I will check to see how challenging it is.

**Comment by uazo** [comment]
new patch [Add-setting-to-invert-tap-and-long-tap.patch](https://github.com/uazo/bromite/commit/221f190cc8be839530fee0282ec4ecc22b09d144)

**Comment by uazo** [comment]
you can find a new flag under accessibility to test whether the solution I have developed actually works.
let me know!

**Comment by JimW1at** [comment]
> you can find a new flag under accessibility to test whether the solution I have developed actually works. let me know!

Brilliant!! I tested this on different websites and this is exactly what i wanted, this solves all the problems. 
Thank you for your effort on this. You are the best.


Just one thing i would like to add that it does not show context menu when i tap on an image, it would be great if this was possible.

Thanks anyway.

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/89427c73fb7c09e9e2aaf457c3cd87710e95ae34

**Comment by JimW1at** [comment]
Hi, thanks again for this update, now context menu also opens with images. Well done.

One last thing, it seems twitter website has a bug, 
when i tap on a username in the timeline page, the context menu does appear instead it simply clicks on the link.... can this be changed or this is a twitter specific thing/bug.

Anyway awesome update and awesome browser.

**Comment by uazo** [comment]
I don't use twitter so I couldn't tell you.
is checked for the presence of an <a> link, if it is not present in the html but navigation is generated with javascript I don't know about making the context menu appear.
you should check with the development tools what is actually in the html.

I ask you a favor, I saw that you made the same request in kiwi. since they don't allow me access to their repo, could you tell them that the patch exists and if they want they can use it? just linking their issue to mine
