### ISSUE TITLE
Round share UI

### ISSUE THREAD

**Issue by ghost** [uazo/bromite-buildtools#122]
![Screenshot_2023-04-02-16-09-30-644_org.bromite.bromite.dev-edit.jpg](https://user-images.githubusercontent.com/71558811/229355219-97e03dd6-72fd-410a-a6af-db77799124fd.jpg)

As you can see, current UI isn't rounded and looks bad.

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/0a175595d78839a65433e029a5ecf1c1aa7df086
