### ISSUE TITLE
How can I help you

### ISSUE THREAD

**Issue by heliophane** [uazo/bromite-buildtools#134]
Hi, sorry if an issue isn't the place to do this, but it's clear that you've taken the mantle of continuing bromite. How can I help you out with development? Do you have a patreon or a liberapay? I can't promise much but I'd like to throw something to you.

**Comment by PF4Public** [comment]
@uazo consider creating testing builds so that more people could test and verify your proposed new patches

**Comment by uazo** [comment]
> consider creating testing builds

this repo is a testing build!

> more people could test and verify your proposed new patches

this can be done

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
