### ISSUE TITLE
[Request] Add armeabi-v7a Application

### ISSUE THREAD

**Issue by gracie95** [uazo/bromite-buildtools#135]

**Comment by Spark4000** [comment]
https://github.com/uazo/bromite-buildtools/issues/41

**Comment by Universalizer** [comment]
Two days ago, first debut of Cromite's architecture build ; arm32-v7a is released as "arm_ChromePublic.apk", check under https://github.com/uazo/cromite/releases.

Your question's final answer.
Thought many people, awaiting for this request is finally over.
