### ISSUE TITLE
Bookmark Export Error

### ISSUE THREAD

**Issue by js290** [uazo/bromite-buildtools#137]
Affects last official release 108 and the latest dev version from here...

1. Export bookmarks from Bromite on one device
2. Copy exported bookmarks to another device with Bromite newly installed
3. Import the bookmarks
4. Unable to complete previous operation due to low memory

[logcat.txt](https://github.com/uazo/bromite-buildtools/files/11187478/logcat.txt)

<details><summary>Details</summary>
<p>

![Screenshot_20230409-231335_Bromite](https://user-images.githubusercontent.com/4715607/230819894-35f4b6f8-2dd1-42f6-8fa0-a01185272d11.png)

</p>
</details>

**Comment by uazo** [comment]
you can try enabling `chrome://flags#export-bookmarks-use-saf` ?

**Comment by js290** [comment]
I think I see the problem... exported bookmarks are zero length.  Changing `chrome://flags#export-bookmarks-use-saf` did not help.

**Comment by uazo** [comment]
> exported bookmarks are zero length

Let me understand, is the problem still there? is it related to export?

**Comment by js290** [comment]
Yeah, I think the problem is the exported bookmark is of zero length.  And, then when I tried to import, I get the `low memory` error as reported.  I did not notice the zero length bookmark export until after I opened this issue.

**Comment by uazo** [comment]
I do not detect any problems with either export or import.
if you export from bromite 108, check that the file is generated at the end. you should also check that when importing into 112 you are selecting the same file.
I'll close the task for now, we can reopen it if you can identify the problem.
