### ISSUE TITLE
Weird issue(s) when installing alongside chromium (of macchrome/droidchrome)

### ISSUE THREAD

**Issue by pitsi** [uazo/bromite-buildtools#138]
Preface: I have been a bromite user for the last ~3 years and, because it is still stuck on v108 on the main repo since December, lately, I am looking for another chromium based browser to replace it... sometime in the future.

I discovered that chromium build ~2 weeks ago, when it was on v111.x, and I installed it the way I always do, via adb (`adb install blablabla.apk`). And a week later, I discovered the development packages for bromite from here.

As expected, when new versions came out for both browsers, I downloaded and installed the new apks. And here starts the wierd stuff: none of the 2 browsers mentions the correct version in either chrome://version (screenshots below) or in the app's info page!
For simplicity reasons, the following are the outputs of apkinfo (info from apk file downloaded locally) and adb shell dympsys package (info from the os) for each one.

Chomium

```
$ apkinfo arm64_ChromePublic_HEVC-112.0.5615.62.apk 
APK: arm64_ChromePublic_HEVC-112.0.5615.62.apk
App name: Chromium
Package: org.chromium.chrome.stable
Version name: 112.0.5615.62
Version code: 561506215

$ adb shell dumpsys package org.chromium.chrome.stable | grep version
    versionCode=561506215 minSdk=24 targetSdk=33
    versionName=112.0.5615.62
```
![Screenshot_20230409-142140](https://user-images.githubusercontent.com/5880037/230769828-bdc59cb5-52f4-4415-8a8a-bcf7a108ddb8.png)

Bromite
```
$ apkinfo arm64_ChromePublic.apk 
APK: arm64_ChromePublic.apk
App name: Chromium
Package: org.bromite.bromite.dev
Version name: 112.0.5615.48
Version code: 561504815

$ adb shell dumpsys package org.bromite.bromite.dev | grep version
    versionCode=561504815 minSdk=24 targetSdk=33
    versionName=112.0.5615.48
```
![Screenshot_20230409-142107](https://user-images.githubusercontent.com/5880037/230769861-8b1a9aa7-9194-4fba-ad8b-71312f83c55a.png)

All the above is stuff that I did yesterday, when I asked the chromium's dev for any ideas and he said "Perhaps the chromium/bromite version is being spoofed".
Fast forward to today. I removed chromium completely and left only bromite installed. I reistalled it the 112.x version from the latest apk, but it still shows 108.x there! 

Any ideas?

**Comment by uazo** [comment]
each apk installs different applications.
so my apk cannot update bromite.

**Comment by pitsi** [comment]
You are probably right. This is what apkinfo returns for the original bromite
```
App name: Bromite
Package: org.bromite.bromite
Version name: 108.0.5359.156
```
and this is what it returns for your dev build
```
App name: Chromium
Package: org.bromite.bromite.dev
Version name: 112.0.5615.48
```
As if it is a different app, although there is no new ion at the launcher. Can't you make it have the same app name and package name so that it upgrades the original bromite?
If not, please add that as a detail in the readme.
