### ISSUE TITLE
Disqus: CSRF verification failed (403).

### ISSUE THREAD

**Issue by Kirshi912** [uazo/bromite-buildtools#143]
I don't have any clue about this CSRF thing, but this issues occured in both bromite till your latest update chromium-bromite (112). 
There is always website that using **disqus** for their comment section plugin, and this issue prevent me from log-in (at least using google and facebook login method). **Chrome doesn't have this problem though**. 
 
I'm using oppo a16, android 12. Non-rooted, no userscript, ad-block off, i already clearing flag in bromite for testing so it's not the cause. This is my only devices, so i cant verify if the same happen on another or if it just me. (So anyone who have the same problem or maybe not, please your feedback).
Not trying to advertise or something but you may use this (isekailunatic. com/2020/02/12/wm-prologue-1-a-class-stranded/) blog example who using disqus. The same happen in another blog that use the same comment section plugin. 

Btw, i can login directly from disqus main web, but not for using their plugin. 

Thanks for update till now. 
![IMG_20230414_194009](https://user-images.githubusercontent.com/130754914/232034382-90550f52-2009-43ae-a33e-f4a9e56220b7.jpg)

**Comment by uazo** [comment]
it is likely that you cannot use that method because of the blocking of third-party cookies.
Please try again with that setting active.
Consider however that, unlike that version of bromite, now you also have cookie partitioning active, which will probably block that type of access.

**Comment by Kirshi912** [comment]
I do allow cookies on site setting, turn off all ad blocker, do something with http refererr setting. But nothing changes, do i miss something?

By the way, I know this unrelated but 'Desktop site' have odd behavior that will automatically on (checked) even if i uncheck it, i don't know what would trigger that or if anyone have that problem thought.

**Comment by uazo** [comment]
to understand this you have to analyze what the site actually does.
should be looked at with debugging tools, but unfortunately I don't have any login on disqus.

I leave it open because it is a usability issue

**Comment by Kirshi912** [comment]
I don't know if you aware but, this issue may resolved long time ago (not that i tested or verify), but i wonder why the last version have the issue back. What i mentioned is bromite and this [discussion](https://github.com/bromite/bromite/issues/470).

**Comment by uazo** [comment]
> but unfortunately I don't have any login on disqus https://github.com/uazo/bromite-buildtools/issues/143#issuecomment-1509672979

I'm sorry, but this is my only problem.
If you are able to reproduce the error without having to register at any site, I will be happy to check.
