### ISSUE TITLE
Bromite x86-x64 build

### ISSUE THREAD

**Issue by steinpigs** [uazo/bromite-buildtools#145]
Can you add x86-x64 support to your releases?

**Comment by uazo** [comment]
yes, but only x64 can be done.

**Comment by steinpigs** [comment]
Thank you. Looking forward to it.

**Comment by uazo** [comment]
I changed the build agent and updated the latest release with the x64 version.

**Comment by uazo** [comment]
From now on, the x64 version will always be present in the releases as well.
