### ISSUE TITLE
v113 crash on startup

### ISSUE THREAD

**Issue by HazakuraID** [uazo/bromite-buildtools#167]
https://user-images.githubusercontent.com/105591857/235685101-04c38979-9348-4338-b4b2-0ca67c9f4a54.mp4

What there this version new 113 issued it's I experience group fully 200+ limits cause of device Vivo Y71

**Comment by uazo** [comment]
try cleaning the application storage, or if you are not able, uninstall and reinstall the application.
we just found a bug in adblock (ref https://github.com/uazo/bromite-buildtools/issues/165), maybe that's why.

**Comment by HazakuraID** [comment]
already this been uninstalled and after installing fixed can it work aslo.
