### ISSUE TITLE
Bottom toolbar causes white stripe at top in tab view, no grid layout

### ISSUE THREAD

**Issue by Gravemind2015** [uazo/bromite-buildtools#168]
It's exactly like what happened in bromite ([issue 2407](https://github.com/bromite/bromite/issues/2407) ) where the tab view changed to list view, and a white stripe shows up if the toolbar is set to bottom.

This time there are no chrome://flags entry for grid tabs, although I'm not sure if they ever were on these beta builds, it had always been grid tabs. 

Funnily enough, my old copy of bromite actually showed this same behaviour now. Maybe a server side switch? Anyway considering the uncertainty around the whole project(s), I just wanted to point this out in case it could lead to further breakage or something.

BTW thanks a ton for continuing the efforts👍

Bromite/Chromium beta version: Chromium 113.0.5672.63
App data cleared and tabs restored through bookmarks after update from version 112.

<details><summary>Details</summary>
<p>

![Screenshot_20230502-225657_Chromium](https://user-images.githubusercontent.com/116586720/235742275-e46c4b16-db5f-4598-8ab4-b7958b3e55ec.png)

</p>
</details>

**Comment by uazo** [comment]
> Maybe a server side switch?

I rule it out; there is no counterpart on the server.
I would rather think about an android update, if anything.

if you can I would need your active flags: you can extract them from  `chrome://local-state/`
CAUTION: Do not post the whole result, only the section as below (this is mine):
```
   "browser": {
      "enabled_labs_experiments": [ "enable-firewall@1", "fill-on-account-select@1", "fingerprinting-client-rects-noise", 
      "page-content-annotations@4", "page-entities-page-content-annotations@3", "private-network-access-respect-preflight-results@2" ],
   },
```

**Comment by Gravemind2015** [comment]
Hey, sorry I should have clarified better. I can confirm no android upgrade (major/minor) happened on the device as they were out of support now. As for active flags:
`{
   "EulaAccepted": true,
   "browser": {
      "enabled_labs_experiments": [ "move-top-toolbar-to-bottom@1" ]
   },
   "hardware_acceleration_mode_previous": true,`
I hope I properly included the relevant part. 

Just to test I clean installed again on both devices, confirmed grid tab was shown and restored the bookmarks & restored tabs from it. It retains grid view. What's weirder is, opening bromite (my old copy) now shows grid tab as well. Just like issue [2407](https://github.com/bromite/bromite/issues/2407) ,  it kinda 'fixed itself' after a few hours. Hopefully it stays this way.

**Comment by uazo** [comment]
>  it kinda 'fixed itself' after a few hours. 

too bad. 
I think a restart of the application was sufficient because the state of the flags must synchronize native with the java part.
if you feel like understanding better, try reinstalling the old version, change the flags and install the new one.
as a guarantee that there is no server, turn off the connection.

I am closing the issue, not being related to privacy, feel free to reopen if you find something interesting

**Comment by Gravemind2015** [comment]
Yeah, maybe a full force stopping of the app might have helped. It only surprised me because bromite (the csagan5 one) showed that symptom and then getting fixed, especially since it hadn't been updated since December 2022😅
Sorry for the unnecessary trouble then, and thanks again for continuing this project.

**Comment by NextDev65** [comment]
https://hirenkvaghasiya.medium.com/how-to-get-back-tab-grid-layout-in-google-chrome-android-march-2023-fc7f0b219b35#:~:text=Steps%20to%20get%20back%20your,Simplified%20view%20for%20open%20tabs%E2%80%9D
The tabs in list mode seems to be default ON when installing chrome, so this affects [Cromite](https://github.com/uazo/cromite) as well. 
Just turn it off in Settings > Accessibility > Simplified view ...
