### ISSUE TITLE
Change name and icon

### ISSUE THREAD

**Issue by 1RandomDev** [uazo/bromite-buildtools#169]
Why not change the icon to the Bromite one and the app name to something like "Bromite Dev" or something more creative. I really want to replace Bromite with this fork, but I have to have plain Chromium installed for one specific application and I always mix those two up.

**Comment by Kirshi912** [comment]
It just my assumptions but it's not permitted.

**Comment by 1RandomDev** [comment]
Oh no I really hope I don't have to make another fork of this fork just to edit some icons so that it looks good at my homescreen.

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
