### ISSUE TITLE
No option to open link in new tab

### ISSUE THREAD

**Issue by eskimododo** [uazo/bromite-buildtools#172]
With the new 113 build on Android, whenever I long press on a link or press a link, it gives me an option to only open in new tab group with no option to open in just a new tab.. is this intended to always open links in tab groups rather than tabs?

**Comment by uazo** [comment]
I would ask you to try the same thing with another chromium based browser v113, to see if it is chromium behaving that way (which I think).

**Comment by bocekm** [comment]
I was looking at the same issue. It used to be possible to disable the tab grouping in the pre-v113 versions through chrome://flags (https://www.getdroidtips.com/disable-chrome-tab-groups-android/) but it's not possible anymore.

Brave has added an option to the context menu to allow opening a new tab outside of a tab group: https://github.com/brave/brave-core/pull/12149.

There's a Chrome help talking about allowing opening tabs outside a tab group on a link long press, starting with v112, but that contradicts what we see in v113 https://support.google.com/chrome/thread/25088351?hl=en&msgid=210535293.

**Comment by bocekm** [comment]
Other related Brave changes:
- https://github.com/brave/brave-core/pull/12919 - adding a new option to Settings to not create new tab groups by default.
- https://github.com/brave/brave-core/pull/18345 - fixing the disablement of tab grouping

**Comment by uazo** [comment]
thanks @bocekm !
I will consider your suggestions in future versions

**Comment by dl12345** [comment]
Yeah, this forced tab-group is insanely annoying. I like a tab grid, but hate tab groups on mobile browsers. +1 for the suggestion of the Brave patch mentioned by @bocekm

**Comment by tp0** [comment]
Chromium 115.0.5780.0 (1146313) from https://chromium.woolyss.com/#android

![Screenshot_20230519-071706-889](https://github.com/uazo/bromite-buildtools/assets/5863551/7192c044-09ad-483d-b3ee-f1e9030f7e0e)

**Comment by aluo-x** [comment]
Currently still broken in bromite v114.0.5735.91, works in chrome 114.

**Comment by aluo-x** [comment]
Sorry, after a restart of bromite this issue is fixed. Not sure what happened previously.

**Comment by uazo** [comment]
I did nothing, the chromium team in 114 changed the flag that activates that functionality by default...
