### ISSUE TITLE
[Feature Request] Ability to rename Tab Group. 

### ISSUE THREAD

**Issue by Kirshi912** [uazo/bromite-buildtools#187]
I remember back then, there is flag named 'Tab grid layout' which allowed user to named group (may not the actual function of that flag) instead showing number of opened tab in each group. I don't know since when and why google remove it or never actually implement it (i mean you need flag that general user won't notice). 
![2](https://user-images.githubusercontent.com/130754914/236704787-7c92b448-0b08-44c8-b3a5-5713f74a6bf4.jpg)
![1](https://user-images.githubusercontent.com/130754914/236704792-19d8e389-b39d-49ad-a6ac-707f5f58d91f.jpg)
As you can see from this image, it really convenient if we have this. Till bromite 108, the feature is still there (but has bug that actually disabled the function and revert the named tab to number again). I wonder if it possible for you to implement it.

By the way, thanks for your works.

**Comment by uazo** [comment]
> there is flag named 'Tab grid layout' which allowed user to named group

you can enable it via chrome://flags/#enable-tab-groups-continuation

**Comment by Kirshi912** [comment]
Yeah, it works. Thanks, but if possible i hope that this feature become 'default' instead optional. Unless if it somehow create flaws on security aspect. I see that it's weird for this something basic and useful are hidden till now.

**Comment by uazo** [comment]
yes, I will make it the default
