### ISSUE TITLE
How can I add more filters

### ISSUE THREAD

**Issue by JohnBetaro** [uazo/bromite-buildtools#188]
Hi, I'm trying to add some more filters but it seems that the app won't apply them, I don't know why, where can I get more filters to add them ? I know there are in the app but that's not enough for removing the adds and the their empty places on the pages.

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt

This is an example I don't know why it does not work, please show me where did you get your filters so I can take a look.

Thank you for your time.

**Comment by GY8VSdYYzvL8-K6T** [comment]
I don't think Bromite supports such AdGuard syntax for custom filters. It supports EasyList syntax, but not AdGuard. I am not sure about hosts-type of lists, but they aren't as complicated as AdGuard types of lists and I hope can be supported.
