### ISSUE TITLE
Unable to download from the website tinywow.com

### ISSUE THREAD

**Issue by marinoalfonz1** [uazo/bromite-buildtools#195]
Unable to download files from the website tinywow.com . It is saying download failed bad certificate.

Version 113.0.5672.63

<details><summary>Details</summary>
<p>

![Screenshot_20230512-135303_Chromium](https://github.com/uazo/bromite-buildtools/assets/85938685/b1400f18-7d2e-43b7-b335-013aa4144826)

</p>
</details>

**Comment by uazo** [comment]
duplicate of https://github.com/uazo/bromite-buildtools/issues/192
