### ISSUE TITLE
Font fingerprinting question

### ISSUE THREAD

**Issue by imagecreation** [uazo/bromite-buildtools#203]
Hello, Thanks for the great job!

I tried to test fingerprinting protection on this http://f.vision/ website and noticed that even with this 
![image](https://github.com/uazo/bromite-buildtools/assets/128193454/42bc3009-f1f2-4379-b14d-7072da5bc4bd)
flag enabled it nearly always shows 
![image](https://github.com/uazo/bromite-buildtools/assets/128193454/ba1768f8-964e-42ec-817d-fc57b62a1f82)
this value. 
I also tried on different PC - same.
Is this expected behavior (same as on Android phones)?

**Comment by uazo** [comment]
> noticed that even with this flag enabled

the flag is enabled by default.

> Is this expected behavior (same as on Android phones)?

I am not clear on the question.
that flag disables support for local fonts, enabling the use of only standard preinstalled fonts according to a [specific list defined by microsoft](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list) (see https://github.com/uazo/bromite-buildtools/issues/52).

I will confirm that I also have `05d8debc3f333ed6` and `f26cc60f2dcd35312e56793569ad674108e256e1` if you open the advanced mode.

> same as on Android phones

in android everyone should have `ab515a28f7a49bf7`
