### ISSUE TITLE
Feature Request - Please add userscript manager like tampermonkey to block adblock detection by websites

### ISSUE THREAD

**Issue by marinoalfonz1** [uazo/bromite-buildtools#208]
Please add userscript managers like tampermonkey, to block adblock detection by websites. This could be a very handy feature. Most websites now have adblock detection scripts which defeats the entire purpose of adblocking.. Extension such as these block the adblock detection in websites 

Tampermonkey extension url -https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en

Tampermonkey website - https://www.tampermonkey.net/

**Comment by Kirshi912** [comment]
Hmm... Did you already know that there is userscript menu on setting? If you requested him to create a script to use... You may asked too much.

**Comment by Kirshi912** [comment]
@marinoalfonz1 if i did not read wrong from description of several script there, the method of blocking not universal though (for example, they needed to manually include the site that have anti-adblock and prevent it from triggering). Although i didn't have a chance to try since i don't want to risk myself.

**Comment by marinoalfonz1** [comment]
> @marinoalfonz1 if i did not read wrong from description of several script there, the method of blocking not universal though (for example, they needed to manually include the site that have anti-adblock and prevent it from triggering). Although i didn't have a chance to try since i don't want to risk myself.

Yes the blocking adblock detection is not  Universal..

**Comment by uazo** [comment]
it seems that adblock plus is already able to do that, but I currently have that function blocked because I haven't checked it yet.
I'll talk about it after activation.

see https://github.com/uazo/bromite-buildtools/issues/84
