### ISSUE TITLE
Bug? Chrome://flags desktop mode only. 

### ISSUE THREAD

**Issue by Kirshi912** [uazo/bromite-buildtools#216]
![Screenshot_2023-05-22-05-47-43-54_bd2501a81f8cb7892bf23f7aa550aba2](https://github.com/uazo/bromite-buildtools/assets/130754914/9cb02e31-69f4-4877-938e-4b79e597d4ac)

Reload didn't do anything.

**Comment by uazo** [comment]
please, I try to be as comprehensive as possible in my answers, I at least ask for the effort to explain the request well
