### ISSUE TITLE
Media Button crashes browser on Windows

### ISSUE THREAD

**Issue by calhix** [uazo/bromite-buildtools#217]
Hello, looks like anytime I have the option to use that media controller button in the top right corner on Windows, it crashes the browser after clicking it every time.

**Comment by uazo** [comment]
![image](https://github.com/uazo/bromite-buildtools/assets/29201891/d64433ae-5dbd-4261-9ddd-b6199c955fce)

thank you, i didn't realize that

**Comment by uazo** [comment]
upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=1444788

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/d625bc358c1c42c91f6a44ebe87b746036904fca
