### ISSUE TITLE
On first startup we need to click the mouse to enter text in windows

### ISSUE THREAD

**Issue by marinoalfonz1** [uazo/bromite-buildtools#221]
On first startup we need to click the mouse to enter text,eventhough the text editor is blinking,is this a bug or is there a workaround for this?

Version - 113.0.5672.127 (64bit) (latest version)

**Comment by marinoalfonz1** [comment]
> On first startup we need to click the mouse to enter text,eventhough the text editor is blinking,is this a bug or is there a workaround for this?
> 
> Version - 113.0.5672.127 (64bit) (latest version)

Doesn't happen with Microsoft edge though (tested)

**Comment by marinoalfonz1** [comment]
https://photos.app.goo.gl/1pLp86Y3StaVuWZw5

Video of the issue can be found here

**Comment by uazo** [comment]
I'm sorry, but I can't reproduce the problem. it works perfectly for me.
Can you check with another pc?

**Comment by marinoalfonz1** [comment]
Can someone else test this please

**Comment by ray-holmium** [comment]
@marinoalfonz1 thanks for pointing this out. I was having the same problem but didn't notice til I saw this issue you created. I was able to fix the problem by applying the registry tweak suggested on [this page](https://forums.ivanti.com/s/article/New-program-window-appears-behind-all-other-open-windows?language=en_US) and rebooting.

**Comment by ray-holmium** [comment]
nevermind, the registry tweak is no longer working after another reboot. But the issue is not confined to this browser. It's happening in firefox and some other programs I've tried as well.
