### ISSUE TITLE
Feature request: The ability to install extensions.

### ISSUE THREAD

**Issue by JohnBetaro** [uazo/bromite-buildtools#222]
The title says it all, like Kiwi browser implemented this feature so we can get extensions from the Chrome Web Store like the PC version, it will be a game changer, Kiwi browser is based on Chromium also and [open source](https://github.com/kiwibrowser/src.next), maybe you can take a look at it to see what you can do.

Please consider my thoughts, thank you for your time

**Comment by uazo** [comment]
no, for now, no intention to enable extensions in android
