### ISSUE TITLE
Feature request: AMOLED Black theme

### ISSUE THREAD

**Issue by Tarshis** [uazo/bromite-buildtools#224]
A solid black theme would make the browsing experience even better for users with devices that have AMOLED displays.

**Feature Details:**
1. Battery Saver: AMOLED displays can turn off pixels to produce true blacks. By adding an AMOLED Black theme, Cromite can save battery life on devices with AMOLED screens.

2. Cool Looks: AMOLED Black themes look sleek and modern. They have a dark background with colorful text and icons that really stand out. It would make browsing more stylish, especially in the dark.

3. Easy on the Eyes: Dark themes can be easier to read and reduce eye strain, especially in low-light environments. By having an AMOLED Black theme, Cromite would be more accessible and comfortable for everyone.

Kiwi Browser has a good implementation of an AMOLED Black theme. It would be great if Cromite's AMOLED Black theme can take inspiration from Kiwi Browser's approach, as it has received positive feedback from users.

Thanks a ton, loving the browser so far!

**Comment by marinoalfonz1** [comment]
If your phone is Android 12+ and has amoled black theme. Then by monet you would get amoled black theme.. (just mentioned it)

**Comment by uazo** [comment]
I don't think I will ever address this point.
sorry.
