### ISSUE TITLE
114 version bromite is Google chrome! 

### ISSUE THREAD

**Issue by dill-shower** [uazo/bromite-buildtools#226]
114 version of bromite turned into Google Chrome

<details><summary>Details</summary>
<p>

![S1](https://github.com/uazo/bromite-buildtools/assets/114938733/46c5534e-f53d-433b-833d-3067477cccc4)
![S2](https://github.com/uazo/bromite-buildtools/assets/114938733/80aa4a02-5784-42f8-a332-4f9097553194)
![S3](https://github.com/uazo/bromite-buildtools/assets/114938733/5da6ba01-aab1-47b9-80ef-b7007c9deb3f)

</p>
</details>

**Comment by dill-shower** [comment]
> It was already like this. ![Screenshot_2023-06-01-19-30-51-948_org.bromite.bromite.dev-edit.jpg](https://user-images.githubusercontent.com/71558811/242665903-ed1b4a58-72a6-4160-8465-b855355d169e.jpg)

Issue about Google services in settings. And enabled analytics

**Comment by uazo** [comment]
thanks for the tip, I hadn't noticed.
will be part of https://github.com/uazo/bromite-buildtools/issues/182

> And enabled analytics

please explain

**Comment by uazo** [comment]
> Uazo has written before that bigger patches would be removed/trimmed (easier to maintain and faster build times maybe?), so I always thought it was intentional.

no faster build time, but if anything slower since code was so far eliminated.
let's say it makes my life easier

>  so I always thought it was intentional.

I haven't actually decided yet whether to delete those entries or simply move them to a separate area, I like the idea that it can be checked that there are no other settings added over time

**Comment by marinoalfonz1** [comment]
No issues in keeping it like this..

**Comment by uazo** [comment]
merged with https://github.com/uazo/bromite-buildtools/issues/182

see https://github.com/uazo/bromite-buildtools/issues/182#issuecomment-1588671032
