### ISSUE TITLE
need 32bit too.

### ISSUE THREAD

**Issue by idontveapc** [uazo/bromite-buildtools#238]

**Comment by uazo** [comment]
see https://github.com/uazo/bromite-buildtools/issues/41

**Comment by idontveapc** [comment]
even after 4 months?!

**Comment by uazo** [comment]
> even after 4 months?!

no, 2 years...

https://github.com/nestybox/sysbox/issues/ 350

**Comment by Universalizer** [comment]
Two days ago, first debut of Cromite's architecture build ; arm32-v7a is released as "arm_ChromePublic.apk", check under https://github.com/uazo/cromite/releases.

Your question's final answer.
Thought many people, awaiting for this request is finally over.
