### ISSUE TITLE
Reviving Bromite into something new...?

### ISSUE THREAD

**Issue by peternrdstrm** [uazo/bromite-buildtools#239]
As of https://github.com/uazo/bromite-buildtools/issues/182, I have noticed effort from Uazo to restore Bromite into a new browser. 
I have historically have been a big fan of Bromite, so I'd love to join this journey, and help as much as I can. 
to begin with, I have a few proposals for the tasks established by Uazo. These are my opinion tho, obviously just a suggestion.

For the browser's goal, I have a few in mind, those being
- Ease of maintainance to minimize the risk of falling behind like Bromite did. 
- Keep the privacy in mind and build on bromite. Improvements could be made to the content blocking and fingerprinting protections.
- Providing a good, cross-platform, out of the box experience, the way Brave does, without it's flaws. 

Licensing is debatable. We could keep GPLv3 and keep going as we did, or alternatively switch to GPLv2. For those confused, Bromite and Vanadium by GrapheneOS used to share some code, but due to some unfortunate miscommunication, Vanadium changed it's licensing to stop Bromite using their code, and them using Bromite's. The reborn version could re-build this, assuming Uazo is okay with doing so.  Relying on Vanadium for *some* security patches could potentially reduce the maintainance efforts. Really sorry, if I triggered anyone by mentioning the thing here, if Uazo finds this unfit for the new project, feel free to delete my issue,

Documentation, I would be more than happy to help with this. I am re-installing it today, and assuming I get some guidelines, to the best of my technical skill and knowleadge, I could help write this. 

I already mentioned the simplification of maintainance, I do not feel qualified to comment on this, my programming *has* improved, but is still unfit for a security-critical project like this one. 

The rest I will comment about once I spend some more time with the browser. Cheers Uazo, I hope you/we can pull this off!

**Comment by uazo** [comment]
my two cents:

> Ease of maintainance to minimize the risk of falling behind like Bromite did.

I think it is possible provided that a real interoperability of patches between different forks is developed, but first a lot of work needs to be done to fix the code. and a series of tests also needs to be developed to convince the developers (including me :) of the goodness of the changes made. The browser must not be manipulated, I often ask myself whether I trust my changes.
For now I am going ahead with this, but sooner or later I will have to seriously think about it.

> Keep the privacy in mind and build on bromite. Improvements could be made to the content blocking and fingerprinting protections

the difficulty here is the evaluation of impacts. lately i follow [w3c tags](https://github.com/w3ctag/design-reviews/issues) to better understand, but it is not always simple. let me give you an example, is [BYOB support for Fetch](https://groups.google.com/a/chromium.org/g/blink-dev/c/I0X6IturxWA) privacy friendly or not?

> Providing a good, cross-platform, out of the box experience, the way Brave does, without it's flaws.

I agree, but don't compare me to Brave's team, we are different things. Brave's team does a good job that outclasses mine by a couple of measures, technically speaking. in comparison, I am no one.

> We could keep GPLv3 and keep going as we did, or alternatively switch to GPLv2

this is to be better understood. for example the eyeo adblock patch is gpl3, theoretically i could not use it with gpl2.
and without BSD3, other forks could not use my patches and improve them.

> Documentation, I would be more than happy to help with this.

absolutely, make as many proposals as you think, everything is welcome

**Comment by NearestWater262** [comment]
maybe new name and logo? :D
