### ISSUE TITLE
[Feature Request] Remove unnecessary folders

### ISSUE THREAD

**Issue by HarriBuh** [uazo/bromite-buildtools#252]
![markup_1000012978](https://github.com/uazo/bromite-buildtools/assets/123186113/d4f497ce-bb23-4964-915b-918fa26ea143)

The two marked folders exist in the bookmark menu since I can remember, yet I have never ever used them. Tbh I don't even know if they were usable (especially the "Read list"-folder) at all.

It's purely cosmetical, so it should be of low priority.

**Comment by uazo** [comment]
>  Tbh I don't even know if they were usable

tabs collection is used by:
![image](https://github.com/uazo/bromite-buildtools/assets/29201891/4c526e5b-5a81-460e-8695-047fc30070a1)

reading list by:
![image](https://github.com/uazo/bromite-buildtools/assets/29201891/2f8fcae1-7ff8-4ab5-8726-d09597e3b779)
