### ISSUE TITLE
Update for Bromite possible?

### ISSUE THREAD

**Issue by Roever1** [uazo/bromite-buildtools#255]
Hi there, 
I used Bromite until now  and i would like to update it directly with your version, is that possible?just executing the apk gave me another chromium. My Bromite version is 108.0.5359.156.
Thanks a lot!

**Comment by uazo** [comment]
>  is that possible?

no. the bromite apk is digitally signed by carl and I don't have the keys available.

> just executing the apk gave me another chromium.

That's how it is for now. when I do https://github.com/uazo/bromite-buildtools/issues/182 the situation will be different.
