### ISSUE TITLE
DAT based ("old") ad blocker

### ISSUE THREAD

**Issue by torvic9** [uazo/bromite-buildtools#262]
Continuation of https://github.com/uazo/bromite-buildtools/issues/256#issuecomment-1602124617

The old ad blocker based on binary indexed DAT files either doesn't work or the generated blocklist is faulty.
I cannot tell what's going on because I have no development/debugging environment here.

I'm using [this freshly generated >10 MB list](https://github.com/torvic9/adfilter/raw/master/filters_big.dat).

**Comment by uazo** [comment]
the error is
```
[WARNING:ruleset_service.cc(332)] RulesetService: failed parsing.
```

this is the procedure:

```
ruleset_converter --input_format=filter-list --output_format=unindexed-ruleset \
                  --input_files=filters.txt --output_file=filters_unindexed
```

and the result
```
lg@0909812219e4:~/chromium/src$ ls -la filters*
-rw-r--r-- 1 lg lg  8005130 Jun 22 10:01 filters_unindexed
```

your file is 14mb so you are using the indexed version, but is wrong. you have to use unindex version.

**Comment by uazo** [comment]
I tried entering the https://github.com/torvic9/adfilter/raw/master/filters.txt url into adblockplus and (now) it is read without any problems.
I recommend you to use this method, also because sooner or later I will disable the "old" adblock.

**Comment by torvic9** [comment]
> you have to use unindex version.

Unindexed doesn't work either, I tested it.

**Comment by uazo** [comment]
> Unindexed doesn't work either, I tested it.

Yes, I noticed that a bug in the code.
Basically if a sentinel file is found in `\data\data\org.bromite.bromite.dev\app_chrome\Subresource Filter`, inserted but not deleted in the case of parsing error, new files can no longer be acquired.
if you can (with a rooted phone) delete the contents of that folder completely and try again.

**Comment by torvic9** [comment]
> Yes, but you will lose everything

That's not a big issue. I can try it later.
