### ISSUE TITLE
Preventing trivial conflicts

### ISSUE THREAD

**Issue by chirayudesai** [uazo/bromite-buildtools#263]
```
  # Three lines of non-changing comments so that
  # the commit queue can handle CLs rolling ios_webkit
  # and whatever else without interference from each other.
code...
  # Three lines of non-changing comments so that
  # the commit queue can handle CLs rolling ios_webkit
  # and whatever else without interference from each other.
```

This was mentioned in #193 

It's used by the Chromium team in certain places where they have scripts to automatically update things without causing conflicts.

**Comment by chirayudesai** [comment]
@uazo I was trying to think where it would make sense to use here.

One is the various places where there's a one-line addition, but just the fact that something is added here to chromium would cause a conflict, but after that it will be fine.

Example:

Patch 1:
* Add the above 3 lines, to avoid conflicts

Patch 2-n:
* Add some feature that depend on each other. With the above, in theory it should be possible to pick any patch without the rest, just need the first patch.


I don't know how beneficial this would be for the purposes of the patches maintained here.

I'll close for now since on further checks this might not be too useful here.

**Comment by uazo** [comment]
> I'll close for now since on further checks this might not be too useful here.

no, please go ahead.
I also tried again recently, but could not find the solution.

> Add some feature that depend on each other. With the above, in theory it should be possible to pick any patch without the rest, just need the first patch.

"Add some feature that depend on each other.", no, I need it for "consequential" patches:

so:
1) patch A: main patch
2) patch B: need patch A --> insert some code
3) patch C: need patch A (but not patch B) --> I need to insert some code in the same location of patch B
4) etc...

**Comment by chirayudesai** [comment]
> "consequential" patches

Yes!

I was looking at the various site settings patches (images/cookies/etc) but it looks like they changed and may not fit into this.


The other thing that might fit is anything adding new flags - they could all be at the same place, in line.

**Comment by uazo** [comment]
> but it looks like they changed and may not fit into this.

yes, just a few days ago.
take a look at https://github.com/uazo/bromite-buildtools/issues/193#issuecomment-1595779308
with this patch [bromite-build-utils.patch](https://github.com/uazo/bromite/blob/next-v114/build/patches/bromite-build-utils.patch#L178) I have solved this problem, but I would like to find an alternative.

> The other thing that might fit is anything adding new flags - they could all be at the same place, in line.

I don't quite understand what you mean, but for flags I would like to use a method similar to [this](https://github.com/uazo/bromite/blob/next-v114/build/patches/00Internal-firewall.patch#L1422) but separating the xml into different files and then merging them with `cpp_bromite_include`.
this would allow me to dynamically create `chrome://flags` (tracked in https://github.com/uazo/bromite-buildtools/issues/157)

**Comment by uazo** [comment]
in the end there is no way.
@chirayudesai my patch works, though, if you're interested.
