### ISSUE TITLE
Cannot sign into bank website

### ISSUE THREAD

**Issue by BugReportI** [uazo/bromite-buildtools#265]
I tried signing into my bank but it does not go through usual login pages.

I tried Firefox and it works so I do not know what problem is with this browser.

**Comment by uazo** [comment]
ah, that's a big problem.
unfortunately I can't help you, even if you tell me the website I won't be able to verify it without access.
sorry, but you'll have to figure out what the problem is yourself.
when you find it, it will be my pleasure to fix it.

**Comment by BugReportI** [comment]
I found out why I could not login to my bank account.

I had to add the specific website link in allowed cookies list.

I block all cookies by default so other users may not encounter this problem.
