### ISSUE TITLE
Filter lists

### ISSUE THREAD

**Issue by BugReportI** [uazo/bromite-buildtools#266]
Are these filters safe to use?

Are they open source or propriety?

<details><summary>Details</summary>
<p>

![Screenshot_20230623-032504_Trebuchet](https://github.com/uazo/bromite-buildtools/assets/120331504/382b2022-fd60-4c6a-a7ac-c5cb7a9ccae1)

</p>
</details>

**Comment by uazo** [comment]
> Are these filters safe to use?

I assume so

> Are they open source or propriety?

the links are public, please try to check and then tell me.
I await your work before closing this issue

**Comment by BugReportI** [comment]
I did some research and found their Github pages and assume they are safe.

I could not find any anything on their Github page saying they are open source, but since it seems to used in this browser and uBlockorigin, I assume easylist is okay to use for open source software at least.

**Comment by uazo** [comment]
> I did some research and found their Github pages and assume they are safe.

thanks for the confirmation.
please, could you also add the links you found for future reference?

**Comment by BugReportI** [comment]
This is the link I found for essylist Github.

https://github.com/easylist/easylist#user-content-fn-1-9fa71a31978a58e3f2d937e557274e65

**Comment by uazo** [comment]
#84
