### ISSUE TITLE
Reports wrong URI to password managers

### ISSUE THREAD

**Issue by alphamaestro555** [uazo/bromite-buildtools#267]
<details><summary>Details</summary>
<p>

![Screenshot_20230624-105414](https://github.com/uazo/bromite-buildtools/assets/90939488/bc61a819-2c9a-4e35-ad44-4032df8ad1cd)

</p>
</details> 

The correct URI doesn't get passed to Bitwarden. I am unsure if this also applies to other password managers.

Instead of for example github.com it shows bromite app URI.

I'm using latest GrapheneOS.

**Comment by felmey** [comment]
+1

**Comment by uazo** [comment]
I assume it is a bug of bitwarden which does not have full android autofill provier support.
you can check it yourself with:
```
setprop log.tag.AwAutofillManager DEBUG
```
and checking the result with bitwarden and keepassdx (the latter works perfectly).
