### ISSUE TITLE
Number of tabs in tab switcher

### ISSUE THREAD

**Issue by BugReportI** [uazo/bromite-buildtools#282]
The number of tabs changes to two in tab switcher if in spilt screen in landscape.

This also happens when you open new window in Chromium.

It only goes back to 3 tabs if I turn auto rotate off and on.

![Screenshot_20230703-113908_Trebuchet_1_Edited](https://github.com/uazo/bromite-buildtools/assets/120331504/05ba9303-9e10-4027-bc9e-16f0cbf8c31e)
![Screenshot_20230703-113856_Trebuchet_1_Edited](https://github.com/uazo/bromite-buildtools/assets/120331504/68b51874-70b6-4a55-967b-21f4cc4e945d)

**Comment by uazo** [comment]
if you check what chromium vanilla does, you will see that it behaves in the same way.
I am closing this as it is not related to privacy issues
