### ISSUE TITLE
How to block bank website from recommending using app?

### ISSUE THREAD

**Issue by BugReportI** [uazo/bromite-buildtools#283]
The Halifax bank website keeps recommending me to use app to login. I click on continue with website but it just takes me back to login.

So I was wandering how do I block Halifax from recommending me to use app to login?

**Comment by PF4Public** [comment]
Do you delete cookies? They may be storing this information in a specific cookie, which you may exclude from removal.

**Comment by PF4Public** [comment]
I meant do you delete cookies upon browser exit or via any other extension? 

I doubt it would be possible to skip this suggestion if this is hard-coded in their backend.
