### ISSUE TITLE
`max-connections-per-host` flag put into wrong section

### ISSUE THREAD

**Issue by PF4Public** [uazo/bromite-buildtools#284]
Even though it has a `kOsAll` qualifier, it is put under `#if BUILDFLAG(IS_ANDROID)`, so would be unavailable on other platforms:
https://github.com/uazo/bromite/blob/268fc830e0c4583e83e5a31669905914e661bc03/build/patches/Add-flag-to-configure-maximum-connections-per-host.patch#L36-L45

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/41f20e3e4f4d1faffe98ec6420813d32ef9fb9f9

thank you, but what are you doing, trying them all?
I don't understand the purpose of this patch, I mean, inside bromite? any thoughts of your own?

**Comment by PF4Public** [comment]
> trying them all?

No, not at all :) Not yet at least :)

>I don't understand the purpose of this patch

Indeed HTTP2 already supports some multiplexing features and the benefits of this patch may fade away as the time goes by, but presently it has some value.

>what are you doing

Nothing special actually. When replacing ungoogled-chromium fingerprinting patches I found out that they are inseparable from ungooled-chromium version of max connections patch, thus I searched whether bromite had one for substitution. Completely randomly I found out that it does not function :)

**Comment by uazo** [comment]
> Indeed HTTP2 already supports some multiplexing features and the benefits of this patch may fade away as the time goes by, but presently it has some value.

But what does that have to do with privacy?

> Completely randomly I found out that it does not function :)

well, lucky me then!

**Comment by PF4Public** [comment]
> But what does that have to do with privacy?

So that was your question!? Nothing :) It has nothing to do with privacy, just some marginal performance improvement.

**Comment by uazo** [comment]
>> But what does that have to do with privacy?
>
> So that was your question!? Nothing :)

thank you, yes :) that's what I wanted to hear!
I will try it out, if I find no difference I will discard it
