### ISSUE TITLE
Timezone override unable to change or set.

### ISSUE THREAD

**Issue by Universalizer** [uazo/bromite-buildtools#285]
Timezone override ; unable to change or set.

Hello, Uazo, thank you, for this excellent browser apk.

As mentioned in current issue heading, Timezone can't be set other than (it is stuck to system default's timezone), even after restarting the browser.

Tried both the options 1) Random (for each page), 2) any option from "Custom timezone list."

For technical information :-

Build Tools Version ; 114.0.5735.199 (573519904),
OS ; Android 13,
OEM Manufacturer Device & Model ; Samsung SM-A146B,
SOC ; Exynos 1330.

Screenshot provided.

<details><summary>Details</summary>
<p>

![Screenshot_20230708_HHMMSS_Chromium](https://github.com/uazo/bromite-buildtools/assets/116723165/7e00aa65-59e4-4a01-8eb9-500739a2cbcb)

</p>
</details>

**Comment by uazo** [comment]
thank you, I hadn't noticed

fixed in https://github.com/uazo/bromite/commit/a0874d05857203cb2a0eefd0519ea3393963c11f

**Comment by NearestWater262** [comment]
@uazo where does one find these settings in the browser??

**Comment by NearestWater262** [comment]
@uazo thank you very much. it seems to work. i would like to have IP matching, as you know, but this is also nice until then, so thank you :)
