### ISSUE TITLE
Default search engine

### ISSUE THREAD

**Issue by sankhababu** [uazo/bromite-buildtools#287]
Hi Uazo 

Can you please add metager.org & startpage search engine in the default list ? 

Certainly, any engine can be added by opening the site and searching within, then making them default.

But in that case, if one have to change temporarily the search engine, the custom engine lost totally. 
Had to start from scratch to make that default again, which is very inconvenient.

So I'm asking for this.

By the way, with last update your ad-block section is simply brilliant, 👏 it is going to be one of the main USP for this built 👍

Best Regards

**Comment by uazo** [comment]
> Can you please add metager.org & startpage search engine in the default list ?

no, sorry, from Carl I learnt that it is not good to add or remove chromium's default search engines, so as not to shift balances that I don't feel like getting into.

> So I'm asking for this.

see https://github.com/uazo/bromite-buildtools/issues/164

> ad-block section is simply brilliant

grazie!
