### ISSUE TITLE
cannot bypass cloudflare turnstile

### ISSUE THREAD

**Issue by rywz** [uazo/bromite-buildtools#291]
after verifying, page reloads itself and asks me to verify captcha again. 

*this doesn't happen in brave and mull
*using the latest release

**Comment by BugReportI** [comment]
This also happens to me on Foxaholic website.

If I use Firefox or Chromium based browser it works.

Version 114.0.5735.199

**Comment by uazo** [comment]
thanks for the tip!
the anomaly is that their [demo](https://demo.turnstile.workers.dev/) works instead.

I have checked and the bug is that that library uses the memory api which [I have disabled](https://github.com/uazo/bromite-buildtools/issues/269).
will be fixed with 115

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/5d2127742066aa128997ffb4c3810ba2a968aabf

**Comment by PF4Public** [comment]
I can confirm it works in 115.
