### ISSUE TITLE
Temporarily enable/disable feature without settings domain settings

### ISSUE THREAD

**Issue by gokulraam** [uazo/bromite-buildtools#299]
This feature is available in privacy browser where we can enable/disable javascript and cookie temporarily for that particular tab. If we visit a new website and not necessarily visit again, we can enable/disable javascript or cookie for the tab without needing to set domain settings.

**Comment by uazo** [comment]
as a first thought I think it's not worth it.
you can always have them deactivated and reactivated by the site setting only for the sites you think are important.
what would you like to get?

**Comment by gokulraam** [comment]
It was more of a convenience that we can toggle javascript or cookie once through an icon and not wanting to turn off again. Can be done as mentioned. Issue can be closed as it does not add nothing new that cannot be achieved with current functionality.
