### ISSUE TITLE
Better website site setting for the website to to be usable.

### ISSUE THREAD

**Issue by BugReportI** [uazo/bromite-buildtools#305]
Is there is a way to improve site settings in a way so it would show all websites that need access to to use website?

I encountered this problem with my bank Halifax and was able to solve it by allow access in site settings to a specified website and I found that Next UK website behaves even worse in that it just keeps reloading since I have not been able to find which website to allow access.

This is not good since it will heat up device since it keeps reloading.

**Comment by BugReportI** [comment]
Okay, I will wait for it to be implemented when you have the time. I will use other browsers in the meantime for these types of websites.

**Comment by uazo** [comment]
https://github.com/uazo/cromite/issues/323
https://github.com/uazo/cromite/issues/268
