### ISSUE TITLE
docker build issues

### ISSUE THREAD

**Issue by LeOS-GSI** [uazo/bromite-buildtools#312]
I'm now on Mint 21. Docker is starting, permission error is gone. but now I'm getting this error
```
ich@ich:/media/ich/exSSD3/gh-runner/bromite-buildtools/images/github-runner$ ./start-runner.sh
Error response from daemon: No such container: gh-proxy
docker: Error response from daemon: unknown or invalid runtime name: sysbox-runc.
```
and is it really needed to create the storage folder in root folder ?? Because then the command is wrong. You need root to create a folder in root

and in .env do I really have to use MY github token ?? With your user name ?!?!
GITHUB_PERSONAL_TOKEN=

**Comment by uazo** [comment]
what would you like to do?

that script is used to activate the build server connected to github.
if you just want to do the build see https://github.com/uazo/bromite-buildtools/issues/59#issuecomment-1454742907

I apologise, I have not yet sorted out the documentation.

**Comment by LeOS-GSI** [comment]
I want build a cromite apk and I don't want build dumb win .exe
