### ISSUE TITLE
Improve Adblock with the cname check

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#313]
Issue 1151047: Expose DNS record CNAME aliases to the SubresourceFilter
https://bugs.chromium.org/p/chromium/issues/detail?id=1151047

**Comment by chengnan049** [comment]
Maybe https://github.com/brave/adblock-rust is a better way, it have better performance

**Comment by uazo** [comment]
> it have better performance

source?

**Comment by uazo** [comment]
the code in chromium is already present, strangely enough the check is done AFTER the actual download of the resource, who knows why.
opened issue in cromite repo
