### ISSUE TITLE
Privacy and security section, fails to open & crash.

### ISSUE THREAD

**Issue by Universalizer** [uazo/bromite-buildtools#315]
Under chrome://flags/

STR (Steps to reproduce) bug,
**This flag
#privacy-sandbox-settings-4,**

if Default or Disabled, (Ok, no problem),

Crashes, If change to any other value,

Crash happens while trying to access ; Settings > Privacy and security will either crash or browser restarts.

Happens in both latest version of Chromium.apk (Build-tools) & Cromite.<hr>

Other Chromium based forks doesn't crash.

**Comment by uazo** [comment]
chromium is full of flags, I can't be responsible if you modify something unsupported, worse if you intend to reactivate an explicitly disabled feature like privacy sandbox.
