### ISSUE TITLE
file://

### ISSUE THREAD

**Issue by patatetom** [uazo/bromite-buildtools#318]
hi,

_first of all, thank you for making `Chromium` available on android._

I'm having a problem that I didn't have with `Bromite` : I can't access an html file stored on my phone.

in the past, I'd put this html file in the `/Android/data/org.bromite.bromite/files/Download/` folder and that was good, but now I can't open it, even if I put the file in then (new) `/Android/data/org.bromite.bromite.dev/files/Download/` folder...

is this normal ?

regards, lacsaP.

**Comment by uazo** [comment]
I think you should use

`/Android/data/org.cromite.cromite/files/Download/`

**Comment by patatetom** [comment]
no matter how hard I look, I don't have this path on my phone.
I tried creating the missing tree with my files explorer, but `Chromium` keeps sending me to Google instead of giving me access to my file.
maybe I didn't install the right apk [archive](https://github.com/uazo/bromite-buildtools/releases/download/v115.0.5790.98-30d36db90516e651c2cd676a677268b3ea7cf75b/arm64_ChromePublic.apk) ?

**Comment by uazo** [comment]
try with https://github.com/uazo/cromite/releases

**Comment by patatetom** [comment]
hi,

thank you for the link that allowed me to install `Cromite`.

I now have the path `/Android/data/org.cromite.cromite/files/Download/`, but I still can't open my local html file : I've switched to another solution that's a bit heavier but solves the problem ([com.phlox.simpleserver](https://play.google.com/store/apps/details?id=com.phlox.simpleserver)).

regards, lacsaP.
