### ISSUE TITLE
WebView support

### ISSUE THREAD

**Issue by Jamminroot** [uazo/bromite-buildtools#323]
Hey, and thanks for your work

Any chance for a built WebView service? It'd be nice to have a replacement for webview too, not just the browser I launch manually.

Have a nice day and sorry if that's a duplicate

**Comment by PF4Public** [comment]
> sorry if that's a duplicate

Unfortunately it is :( Look here: https://github.com/uazo/cromite/issues/159

**Comment by Jamminroot** [comment]
Sorry about that then!
Closing the issue
