### ISSUE TITLE
Check kEnableADPFRendererMain

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#326]
new flag in 116

```
// If enabled, Chrome includes the Renderer Main thread(s) into the
// ADPF(Android Dynamic Performance Framework) hint session.
```

> This change gives +10-15% increase to the speedometer score. Repro steps:
> - Build with Android high end arm64 build flags, with and without this patch
> - Run speedometer, easier manually or using crossbench on a device with APDF support
see https://source.chromium.org/chromium/chromium/src/+/e7507d15614ac7f499fb89086b3a09772fa8deb4

https://github.com/uazo/bromite-buildtools/issues/309

@Alex313031 perhaps of interest to you

**Comment by uazo** [comment]
activated in cromite

**Comment by Alex313031** [comment]
@uazo Thanks. Set to enabled by default?

**Comment by uazo** [comment]
yes, see https://github.com/uazo/cromite/blob/master/build/patches/00Enable-Android-Dynamic-Performance-Framework.patch
