### ISSUE TITLE
docker run fails

### ISSUE THREAD

**Issue by LeOS-GSI** [uazo/bromite-buildtools#334]
Hi I have followed you howto (without point 6, because I only want build for android). But I can't start docker. getting this error:

```
ich@ich:~/gh-runner/bromite-buildtools/images/github-runner$ cd bromite-buildtools/images/github-runner/
./start-runner.sh
bash: cd: bromite-buildtools/images/github-runner/: File or folder not found
Error response from daemon: No such container: gh-proxy
docker: Error response from daemon: unknown or invalid runtime name: sysbox-runc.
See 'docker run --help'.
```

**Comment by LeOS-GSI** [comment]
I have tried once more. here you can find the full step by step terminal output
[docker-log.txt](https://github.com/uazo/bromite-buildtools/files/12545258/docker-log.txt)

**Comment by uazo** [comment]
> invalid runtime name: sysbox-runc.

you must install sysbox or modify the script to use the standard docker runtime.

attention! you had published your token, delete it from github as soon as possible.

**Comment by LeOS-GSI** [comment]
it's not my real token ;)

**Comment by LeOS-GSI** [comment]
Sorry, still not working. Download was running but now next problem
[docker-log.txt](https://github.com/uazo/bromite-buildtools/files/12545955/docker-log.txt)

**Comment by uazo** [comment]
It works perfectly for me.
but you should use the cromite repo, not the bromite-buildtools one

**Comment by LeOS-GSI** [comment]
Sorry, I don't get it. How should I use the cromite repo? there are no docker stuff in it.

> It works perfectly for me.

Could it be that it isn't working for me, because my token is not fitting to your git user name ??

**Comment by LeOS-GSI** [comment]
I think this part is the problem. I think It will only work with YOUR Token
GITHUB_PERSONAL_TOKEN=<git-token>
GITHUB_OWNER=uazo
GITHUB_REPOSITORY=bromite-buildtools
RUNNER_LABELS=dev
ALLOWEDAUTHORSLIST=uazo

**Comment by uazo** [comment]
> there are no docker stuff in it.

under `/tools` folder.

> I think It will only work with YOUR Token

no, there is no reason why it should not work with yours.

> GITHUB_PERSONAL_TOKEN=
GITHUB_OWNER=uazo
GITHUB_REPOSITORY=bromite-buildtools
RUNNER_LABELS=dev
ALLOWEDAUTHORSLIST=uazo

you have to modify that data by entering your repo and login.

**Comment by LeOS-GSI** [comment]
> under `/tools` folder.

Yes, I have found, but when I'm using that folder I'm getting a proxy error. 

> no, there is no reason why it should not work with yours.

Sure, there is, because my Token is corresponding to jarvey186 and not to uazo.



> you have to modify that data by entering your repo and login.

I can't use my github login data, because I don't have these repositories.



But we can stop here. This building instructions are not working for others and are hard code to be on users HOME folder. So I will once more stop here. thx

**Comment by uazo** [comment]
>  This building instructions are not working for others and are hard code to be on users HOME folder.

you are free to make improvements, I will gladly evaluate them.

**Comment by LeOS-GSI** [comment]
> you are free to make improvements, I will gladly evaluate them.

yeah, I would be happy if I could do. But I have zerro knowledge about docker. I'm a old school builder. 'make' is the magic word ;)
