### ISSUE TITLE
Feedbacks on the Windows version

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#34]
are welcome :)

**Comment by quyleanh** [comment]
Just side question. Could this build survive when MV3 officially launched? Thank you.

**Comment by uazo** [comment]
strange question... why do you ask?
Anyway, that's the idea, also because personally I don't use anything else now...

**Comment by quyleanh** [comment]
I just want to have another option beside Firefox.
Really hope there will be a build with integrated adblock to avoid limitations of MV3.

**Comment by uazo** [comment]
don't worry, it will be there. 
but I remind you that chrome and firefox are reliable, I can never be as reliable as them.

**Comment by quyleanh** [comment]
Yeah. I know but I prefer a good UX browser than reliable browser. When I get used to with customizations and other stuffs, I can't go back...

**Comment by ViktorKahu** [comment]
Would it be too much to ask/hard to do to adapt it to/make an arch linux version?

**Comment by uazo** [comment]
> make an arch linux version?

I am sorry, but I am not able to do that.

**Comment by macchrome** [comment]
When cross-compiling :

The crashing on the chrome://settings/  can be solved thus (before or after gn gen):

=============================

#!/bin/sh

echo Set $1 build for colour picker
 
if [ $1 = win ]; then
sed -i '10s/.*/#include \"out\/default\/gen\/chrome\/grit\/generated_resources.h\"/'  chrome/browser/new_tab_page/chrome_colors/selected_colors_info.h
echo out/default/gen/chrome/grit/generated_resources.h
fi
if [ $1 = mac ]; then
sed -i '10s/.*/#include \"out\/mac\/gen\/chrome\/grit\/generated_resources.h\"/'  chrome/browser/new_tab_page/chrome_colors/selected_colors_info.h
echo out/mac/gen/chrome/grit/generated_resources.h
fi
if [ $1 = linux ]; then
sed -i '10s/.*/#include \"chrome\/grit\/generated_resources.h\"/'  chrome/browser/new_tab_page/chrome_colors/selected_colors_info.h
echo chrome/grit/generated_resources.h
fi

**Comment by uazo** [comment]
> The crashing on the chrome://settings/ can be solved thus

I don't detect any crashes

**Comment by macchrome** [comment]
I've just re-downloaded 112.0.5615.48 Windows Bromite:

1. Try: chrome://settings/?search=hello

2. Try: chrome://settings/manageProfile

If you have no problems then fair enough.

**Comment by uazo** [comment]
ah, ok, I am aware of those. they will be fixed when I remove the larger removal patch.

**Comment by imagecreation** [comment]
New v113 update on Windows doesn't play any sound. Tried on yewtu.be, youtube.com etc

**Comment by uazo** [comment]
thanks for the report but I don't detect any audio problem.

![image](https://user-images.githubusercontent.com/29201891/235650256-53522f24-15c9-4fe7-a480-2db2da716d70.png)
please check if you happen to have the "mute" on

**Comment by NePoCz** [comment]
Hi, just installed it and seems to work fine so far. But I am unable to use it when the system proxy is set to a PAC file ("setup script" in Windows settings). Not sure if it is my environment, so can anyone confirm? The same setup works fine with e.g. ungoogled-chromium

**Comment by uazo** [comment]
> system proxy is set to a PAC file

try to use `chrome://proxy` for setup

**Comment by NePoCz** [comment]
Thanks, didnt know about this proxy settings page. Unfortunatelly still the same problem, setting the PAC here does not help (I made sure the PAC is downloadable!). But setting the proxy directly does work at least.

Overall the proxy settings are a bit strange - for example the extension Proxy SwitchyOmega seems to have no effect at all.
But updating Windows proxy settings (other than PAC) seems to also work fine, so not sure here the problem is

**Comment by NePoCz** [comment]
You are right, this is what is logged (happens for both system settings as well as for Bromite settings):
```
[31972:11124:0508/151311.591:INFO:url_request_http_job.cc(554)] ---ABORTED URLRequestHttpJob: proxy_config_settings(136468456) url: https://raw.githubusercontent.com/mtlive/Adblock-pac/master/proxy.pac path: components/proxy_config/pref_proxy_config_tracker_impl.cc
[31972:11124:0508/150519.083:INFO:url_request_http_job.cc(554)] ---ABORTED URLRequestHttpJob: proxy_config_system(11258689) url: https://raw.githubusercontent.com/mtlive/Adblock-pac/master/proxy.pac path: components/proxy_config/pref_proxy_config_tracker_impl.cc
```

**Comment by uazo** [comment]
thanks, I will add those rules to the firewall https://github.com/uazo/cromite/issues/335

**Comment by uazo** [comment]
> I want to download something it fails with Failed - Bad certificate error.

@imagecreation  I think it is a different call, please open a new issue and check the log.
