### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by blogmangit** [uazo/bromite-buildtools#39]
Hi there, At present the chromium icon is adaptive but with a white background is it possible to implement a chromium icon with full logo background like you guys did on bromite I mean no white background.

Thanks for this magnificent build.

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
