### ISSUE TITLE
Confused about two Adblock settings 

### ISSUE THREAD

**Issue by fynks** [uazo/bromite-buildtools#40]
There are two Adblock settings in the settings menu now. One that was present in bromite itself and second one which is present only in builds of this repository.
I'm confused about which one to use and is anyone of these better than other?
I'm sorry I'm pretty new to this 🙏
Screenshot is attached below:

![1676305997367](https://user-images.githubusercontent.com/75840152/218517057-0daa139b-ed7b-4cea-bf1b-f6269855c876.jpg)

**Comment by uazo** [comment]
> There are two Adblock settings in the settings menu now. One that was present in bromite itself and second one which is present only in builds of this repository.
I'm confused about which one to use and is anyone of these better than other?

the first is the standard bromite, the second is eyeo adblock plus integrated into the browser with most of its features active (is still under development).
the former supports network blocking, the latter network blocking and cosmetic filters

**Comment by fynks** [comment]
Okay okay now i got it thanks a lot
I'm closing this issue now
