### ISSUE TITLE
arm-v7

### ISSUE THREAD

**Issue by lowtrucks** [uazo/bromite-buildtools#41]
hello,

can you please also build arm-v7 version of current Bromite?

thanks.

**Comment by uazo** [comment]
no, sorry. my current build system does not allow this due to an issue in sysbox

**Comment by IntoTheVoid-900** [comment]
anyone know of a similar project but for arm-v7?

**Comment by Universalizer** [comment]
Two days ago, first debut of Cromite's architecture build ; arm32-v7a is released as "arm_ChromePublic.apk", check under https://github.com/uazo/cromite/releases.

Your question's final answer.
Thought many people, awaiting for this request is finally over.
