### ISSUE TITLE
"Aww snap" on every page

### ISSUE THREAD

**Issue by ckbaudio** [uazo/bromite-buildtools#44]
Would be nice to use this fork but I am getting the "Aww Snap" on every page. Chrome still works. 

Android 13 build number
T2B3.230109.004

**Comment by uazo** [comment]
if you can find the Android 13 QPR2 Beta 3.1 for the avd x64 emulator I can check it out, but I have not found it.
until then, there is nothing I can do about it, I don't have a device with that android version and on browserstack it is not available.
