### ISSUE TITLE
110: CCT Dynamic Features (enabled by default)

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#45]
[Enabled](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/flags/android/chrome_feature_list.cc;drc=e14364652369744ed1a8b9c4a582f11833b35aff;bpv=1;bpt=1;l=541?q=kCCTIntentFeatureOverrides&ss=chromium%2Fchromium%2Fsrc) by default.

```
    /** Whether Dynamic Features are enabled. CCT Intents can override the feature set. */
    private boolean mIsDynamicIntentFeatureOverridesEnabled =
            ChromeFeatureList.sCctIntentFeatureOverrides.isEnabled();
```

see https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/src/org/chromium/chrome/browser/customtabs/CustomTabsConnection.java;l=1330;drc=e14364652369744ed1a8b9c4a582f11833b35aff;bpv=1;bpt=1

**Comment by uazo** [comment]
also [kCctAutoTranslate](https://source.chromium.org/chromium/chromium/src/+/main:components/language/core/common/language_experiments.cc;l=48;drc=e14364652369744ed1a8b9c4a582f11833b35aff;bpv=1;bpt=1?q=CCTAutoTranslate&ss=chromium%2Fchromium%2Fsrc)

```
# CCT support for auto-translating to a predefined target language.
# Adds CCT support for auto-translation to a predefined target language
# from allowed packages. This is done via a new intent extra.

```

**Comment by quyleanh** [comment]
Sorry but this means I can have translation function in the future version?

**Comment by uazo** [comment]
no, I don't think so. the translation function integrated in chromium only works with google api.

**Comment by uazo** [comment]
Disabled with https://github.com/uazo/bromite/blob/next-v110/build/patches/00110-ADDTO-Add-custom-tab-intents-privacy-option.patch (fixup version)
