### ISSUE TITLE
AudioFingerprint problem?

### ISSUE THREAD

**Issue by random452** [uazo/bromite-buildtools#56]
If I visit https://audiofingerprint.openwpm.com/ and click Fingerprint me page just freezes infinitely, consuming CPU. I guess this is bug, because on old bromite from stock repo everything is great. Also same with http://f.vision , freeze on opening page

**Comment by uazo** [comment]
thanks for the report, I will check.

**Comment by uazo** [comment]
the bug is related to the fact that, erroneously, the modification of the audio buffer values is done at each `getChannelData()` request.
the change only needs to be made once, as soon as the buffer is available from the audiobus

**Comment by uazo** [comment]
fixed with https://github.com/uazo/bromite-buildtools/issues/50#issuecomment-1436025753
