### ISSUE TITLE
Site loading issue

### ISSUE THREAD

**Issue by sankhababu** [uazo/bromite-buildtools#57]
Hi Uazo
Great initiative.
After latest update I found the popular fingerprint checking website https://www.deviceinfo.me/ don't loading fully. 
Could you look after please ?

**Comment by uazo** [comment]
I confirm that something is not working.
thanks for the report, I will check.

**Comment by uazo** [comment]
same as https://github.com/uazo/bromite-buildtools/issues/56
the problem seems to be due to 'chrome://flags/#fingerprinting-audio-context-data-noise'.

**Comment by sankhababu** [comment]
Confirming - 
Enabling audio fingerprint, by disabling 'Enable Audio Context fingerprint deception' flag, makes  site (https://www.deviceinfo.me/) working.

**Comment by uazo** [comment]
OK, thanks for the confirmation. I close in favour of #56
