### ISSUE TITLE
Allow an easy build

### ISSUE THREAD

**Issue by Universalizer** [uazo/bromite-buildtools#59]
Hello, @uazo

i don't want to burden or bother you,

may i use it ?

if it's possible for you, to release 32-bit build,

Ultimately, your choice and will,

Thank You.

**Comment by uazo** [comment]
no, see https://github.com/uazo/bromite-buildtools/issues/41

**Comment by uazo** [comment]
..but if you have a linux machine I can give you the directions to build it

**Comment by IntoTheVoid-900** [comment]
@uazo How long would it take to build on an 11th gen i7 and a RTX 3050 mobile?

**Comment by uazo** [comment]
> how long would it take to build on an 11th gen i7 and a RTX 3050 mobile

I really don't know.
you can see the times on my build machine, which is an old dual Xeon E5-2650 server (32 cores) with 48 gb of ram.
Experience tells me that the more cores the better, but you have to have 1gb of ram per core.
As far as I know, a good video card is not needed.

> I would like the build instructions please

let's try. Please give me some time to organise.

**Comment by IntoTheVoid-900** [comment]
Sheesh, that is *slightly* higher specced that my laptop lol

**Comment by uazo** [comment]
think, that at the beginning it took me 1 day to compile... then I got tired and asked for an old server...
do you still want to try?

**Comment by IntoTheVoid-900** [comment]
Oh, that's a lot longer than I expected. I think ill give it a shot though, but maybe over the weekend.

**Comment by uazo** [comment]
> I am running Vanilla OS, which has a handy feature called APX which allows you to open full performance containers of Ubuntu, Fedora, Arch, Alpine and Void, so I can use build guides for any of those distros. If I could also make a Linux desktop built at the same timr (preferably as a Flatpak or AppImage) similar to your Windows build that would be great.

What I can provide you with is a docker image, in which you can launch the build with a single command.

> If I could also make a Linux desktop built at the same timr (preferably as a Flatpak or AppImage) similar to your Windows build that would be great.

I do not have the knowledge, I would not be able to test it

> What specs did the device you originally used have?

I am sorry, but I do not remember

**Comment by IntoTheVoid-900** [comment]
> What I can provide you with is a docker image, in which you can launch the build with a single command.
Would that work with Podman? Podman is supposed to be mostly Docker compatible iirc, and it works much better on Vanilla. If not, don't worry, Ill figure out getting Docker properly working.
> I do not have the knowledge, I would not be able to test it
Don't worry, I won't do that because it would seriously increase the build time, right? Ill just stick to Firefox with UBO on desktop.

**Comment by uazo** [comment]
>  If not, don't worry, Ill figure out getting Docker properly working.

yes please, I have invested a lot of time in creating my infrastructure, and for now I have no intention of changing.

> Don't worry, I won't do that because it would seriously increase the build time, right? Ill just stick to Firefox with UBO on desktop.

I don't understand, sorry but my English is faltering.
I don't create a linux version because I don't have the skills.

> would it be a better option for the building considering the device would be dedicated to the job

you just have to try.

**Comment by IntoTheVoid-900** [comment]
> yes please, I have invested a lot of time in creating my infrastructure, and for now I have no intention of changing.

Okay, it's all good.

> I don't understand, sorry but my English is faltering.
I don't create a linux version because I don't have the skills.

I meant that I would try to do it myself, but I won't anymore because it would mean each build would take much longer because it is building for Android and Linux.

> you just have to try.

Okay, Ill play around with it myself until I find a way that works for me.

**Comment by IntoTheVoid-900** [comment]
> Your english is simple, straight forward, satisfactory and good enough, unnecessarily you are criticizing and hurting your own self.
Don't loose your own language confidence.
Practice consistently makes human perfect, automatically you will gain confidence.

I agree with everything OP said. I honestly could not tell that you were not a native English speaker until you said that, because you have had really good English.

**Comment by uazo** [comment]
we can test the build, follow these steps:

1. create the docker container:
```
docker create --name build --entrypoint "tail" uazo/bromite-build:7890942dfae56b4a5a55497102a9d8b14cb4374b "-f" "/dev/null"
docker start build
```
the image will take about 60gb.
if you want you can inhibit internet access in the container because the image already has all the prerequisites and the build is done without network access.

2. with `docker exec -ti build bash` enter the newly created container and write:

```
WORKSPACE=/home/lg/working_dir
PATH=$WORKSPACE/chromium/src/third_party/llvm-build/Release+Asserts/bin:$WORKSPACE/depot_tools/:/usr/local/go/bin:$WORKSPACE/mtool/bin:$PATH
export HOME=/home/lg/working_dir
cd $HOME
export KYTHE_CORPUS=chromium.googlesource.com/chromium/src
export KYTHE_ROOT_DIRECTORY=/home/lg/working_dir/chromium/src
export KYTHE_OUTPUT_DIRECTORY=/home/lg/working_dir/chromium/src/out/bromite/kythe
export DEPOT_TOOLS_WIN_TOOLCHAIN_BASE_URL=/win_sdk/10.0.20348.0/
export WINDOWSSDKDIR=/win_sdk/10.0.20348.0/Windows\ Kits/10/
export GYP_MSVS_OVERRIDE_PATH=/win_sdk/10.0.20348.0/
cd chromium/src/
```
so you have everything ready.

3. now you can launch gn and the build, for example:

```
gn gen --args="import(\"/home/lg/working_dir/bromite/build/bromite.gn_args\") $(cat ../../build_args.gni) " out/bromite 
date && autoninja -C out/bromite chrome_public_apk && date || date

```

**Comment by IntoTheVoid-900** [comment]
Okay, Ill try that soon. I wont be able to this week now, because I will need my laptop every day and this seems like it will take more than 12 hours, but I should be able to try next weekend.

**Comment by tsetmeup** [comment]
I managed to build an apk using your instructions, @uazo . Thank you very much! Cleaning all browsing data on exit/startup is literally the last feature I needed to make Bromite perfect to me, so thank you very much for that too!

I don't know if you're even looking into it or not, but I hope you get sysbox figured out so you can build arm7 apks too.

**Comment by tsetmeup** [comment]
Ryzen 5 5600x, 1660 Super, 16gb of DDR4 RAM, running Arch. Build time was between 3~5 hours.

The apk itself is outdated, I'm guessing it's because docker doesn't self-update.

Wouldn't it be possible to get github actions to make arm7 apks, without sysbox? I have no idea how compiling or git works, so maybe I'm asking something dumb. But considering how easy it was to build on my PC, without any knowledge, I would guess so.

**Comment by uazo** [comment]
> But considering how easy it was to build on my PC, without any knowledge, I would guess so.

I'm glad to read this, it means that all the mess I've made is working!

> I'm guessing it's because docker doesn't self-update.

images are created for each build. I could do the upload automatically.

> Wouldn't it be possible to get github actions to make arm7 apks, without sysbox?

I think about it

**Comment by uazo** [comment]
you can use `uazo/bromite-build:112.0.5615.121-aafba8c4d858ec2c476ce10c0f6a212de384bb4d` in docker create at https://github.com/uazo/bromite-buildtools/issues/59#issuecomment-1454742907 for latest release

**Comment by uazo** [comment]
if you mean can **you** do the 32bit build, the answer is yes
if you mean can **I** do that build the answer is, for now, no.

**Comment by tsetmeup** [comment]
Thank you for the updated docker image, uazo! I paid attention this time, it took 4 hours to build.

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182

**Comment by LeOS-GSI** [comment]
> 2\. with `docker exec -ti build bash` enter the newly created container and write:

do I need this ??  I don't wont build windoof shit. I want build Android apk

**Comment by uazo** [comment]
> do I need this ?? I don't wont build windoof shit. I want build Android apk

has nothing to do with it, and please don't ask me for details.
you can find information about how docker works on their site.

**Comment by LeOS-GSI** [comment]
> > do I need this ?? I don't wont build windoof shit. I want build Android apk
> 
> has nothing to do with it, and please don't ask me for details. you can find information about how docker works on their site.

I have given up. Docker doesn't work for me. it seems, all is created to work on/ with root directory, but I'm building on second and 3rd ssd's.
