### ISSUE TITLE
Fingerprinting

### ISSUE THREAD

**Issue by random452** [uazo/bromite-buildtools#60]
Thank you for fixing audio fingerprinting bug!
Are you planning to add more active fingerprinting protection layers?
Now I found that font fingerprints and plugins are not spoofed

**Comment by uazo** [comment]
> Are you planning to add more active fingerprinting protection layers?

certainly, as soon as I discover them.

> Now I found that font fingerprints and plugins are not spoofed

is true for [local fonts](https://github.com/uazo/bromite-buildtools/issues/52)
for `navigator.plugins` currently the returned values are empty in android and a constant in windows, so not subject to fingerpriting.
If you find different values, let me know.
