### ISSUE TITLE
Webview*

### ISSUE THREAD

**Issue by azR-103** [uazo/bromite-buildtools#62]
If possible can you please also add support for webview update?

**Comment by uazo** [comment]
No, I do not currently have any apps on my device that use webview, so I would not be able to test it.

**Comment by azR-103** [comment]
https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en_US

^You can use this app to test webview.

**Comment by uazo** [comment]
Yes, okay, I guess there are test apps :)
But I don't use webview in any app, it is not, for now, of my interest to develop it.
