### ISSUE TITLE
Turning down omahaproxy.appspot.com on March 31, 2023

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#63]
it is necessary to modify https://github.com/uazo/bromite-buildtools/blob/dda7cece8f882571d93d973de4459ebf9709649a/.github/workflows/build-images.yaml#L59

see https://groups.google.com/a/chromium.org/g/chromium-dev/c/uH-nFrOLWtE

**Comment by uazo** [comment]
postponed to April 14, 2023

**Comment by uazo** [comment]
we can use https://chromiumdash.appspot.com/fetch_releases?num=1 (and https://chromiumdash.appspot.com/fetch_version?version=110.0.5481.61)

**Comment by PF4Public** [comment]
You can use `curl -s 'https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions/all/releases?filter=endtime=none&order_by=version%20desc'  | jq -rc '.releases | first | .version'` as [used in ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium/blob/5bf56b199816e5ddb3bab7d0a495c695c0a073e7/.github/workflows/new_version_check.yml#L26-L28).

**Comment by uazo** [comment]
thank you!
i just need to add the higher version between android and windows, because to date I recompile both to the latest version
