### ISSUE TITLE
Is your build stable enough for daily use?

### ISSUE THREAD

**Issue by blogmangit** [uazo/bromite-buildtools#67]
Is your build stable enough for daily use ? I mean can I replace your build with bromite which lacks update recently.

**Comment by uazo** [comment]
> Is your build stable enough for daily use ?

Personally, I have been using it for a long time.

>  I mean can I replace your build with bromite which lacks update recently.

it is not my intention to propose a replacement for bromite, then do as you wish.
I hope carl will be in touch soon
