### ISSUE TITLE
Disable vulnerable ciphers

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [uazo/bromite-buildtools#73]
Site https://browserleaks.com/ssl shows many vulnerable ciphers can still be used in Chrome/Bromte:

TLS_ECDHE_RSA_WITH_AES_128_CBC_SHACBC, SHA-MACTLS 1.0,1.1,1.2
0xc014TLS_ECDHE_RSA_WITH_AES_256_CBC_SHACBC, SHA-MACTLS 1.0,1.1,1.2
0x009cTLS_RSA_WITH_AES_128_GCM_SHA256NO PFSTLS 1.2
0x009dTLS_RSA_WITH_AES_256_GCM_SHA384NO PFSTLS 1.2
0x002fTLS_RSA_WITH_AES_128_CBC_SHACBC, SHA-MAC, NO PFSTLS 1.0,1.1,1.2
0x0035TLS_RSA_WITH_AES_256_CBC_SHACBC, SHA-MAC, NO PFSTLS 1.0,1.1,1.2

Ciphers I list abve can be easily disabled in Firefox (on PC at least). I think disabling them for Bromite would be a great security addition!

**Comment by uazo** [comment]
thank you. it should be possible to deactivate them.

to be checked:
https://source.chromium.org/chromium/chromium/src/+/main:net/socket/ssl_server_socket_impl.cc;l=1003;drc=6b0521a0cc765657c70a5a96df666120e1078ceb;bpv=1;bpt=1

ref: https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#SSL_CTX_set_strict_cipher_list

**Comment by uazo** [comment]
there is an underlying problem to assess, changing the handshake mode of ssl produces a new fingerprinting vector.
we would be the only browser not to accept those protocols.
note: we are actually **already easily recognisable** today because the list of enabled protocols is different from other chromium-based browsers, to be investigated.

chrome/edge/brave:
```
0x6a6a TLS_GREASE_6A GREASE
0x1303 TLS_CHACHA20_POLY1305_SHA256 Recommended TLS 1.3
0x1301 TLS_AES_128_GCM_SHA256 Recommended TLS 1.3
0x1302 TLS_AES_256_GCM_SHA384 Recommended TLS 1.3
0xcca9 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 Recommended TLS 1.2
0xcca8 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 Recommended TLS 1.2
0xc02b TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 Recommended TLS 1.2
0xc02f TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 Recommended TLS 1.2
0xc02c TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 Recommended TLS 1.2
0xc030 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 Recommended TLS 1.2
0xc013 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA CBC, SHA-1 TLS 1.0,1.1,1.2
0xc014 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA CBC, SHA-1 TLS 1.0,1.1,1.2
0x009c TLS_RSA_WITH_AES_128_GCM_SHA256 NO PFS TLS 1.2
0x009d TLS_RSA_WITH_AES_256_GCM_SHA384 NO PFS TLS 1.2
0x002f TLS_RSA_WITH_AES_128_CBC_SHA NO PFS, CBC, SHA-1 TLS 1.0,1.1,1.2
0x0035 TLS_RSA_WITH_AES_256_CBC_SHA NO PFS, CBC, SHA-1 TLS 1.0,1.1,1.2
```

bromite:
```
0xbaba TLS_GREASE_BA GREASE
0x1301 TLS_AES_128_GCM_SHA256 Recommended TLS 1.3
0x1302 TLS_AES_256_GCM_SHA384 Recommended TLS 1.3
0x1303 TLS_CHACHA20_POLY1305_SHA256 Recommended TLS 1.3
0xc02b TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 Recommended TLS 1.2
0xc02f TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 Recommended TLS 1.2
0xc02c TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 Recommended TLS 1.2
0xc030 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 Recommended TLS 1.2
0xcca9 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 Recommended TLS 1.2
0xcca8 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 Recommended TLS 1.2
0xc013 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA CBC, SHA-1 TLS 1.0,1.1,1.2
0xc014 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA CBC, SHA-1 TLS 1.0,1.1,1.2
0x009c TLS_RSA_WITH_AES_128_GCM_SHA256 NO PFS TLS 1.2
0x009d TLS_RSA_WITH_AES_256_GCM_SHA384 NO PFS TLS 1.2
0x002f TLS_RSA_WITH_AES_128_CBC_SHA NO PFS, CBC, SHA-1 TLS 1.0,1.1,1.2
0x0035 TLS_RSA_WITH_AES_256_CBC_SHA NO PFS, CBC, SHA-1 TLS 1.0,1.1,1.2
```

**Comment by uazo** [comment]
in order to eliminate them, as a future reference:
```
diff --git a/chrome/browser/ssl/ssl_config_service_manager.cc b/chrome/browser/ssl/ssl_config_service_manager.cc
index a50fab9040..d5e0971a22 100644
--- a/chrome/browser/ssl/ssl_config_service_manager.cc
+++ b/chrome/browser/ssl/ssl_config_service_manager.cc
@@ -77,6 +77,12 @@ std::vector<uint16_t> ParseCipherSuites(
     }
     cipher_suites.push_back(cipher_suite);
   }
+  cipher_suites.push_back(0xc013); // TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
+  cipher_suites.push_back(0xc014); // TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
+  cipher_suites.push_back(0x009c); // TLS_RSA_WITH_AES_128_GCM_SHA256
+  cipher_suites.push_back(0x009d); // TLS_RSA_WITH_AES_256_GCM_SHA384
+  cipher_suites.push_back(0x002f); // TLS_RSA_WITH_AES_128_CBC_SHA
+  cipher_suites.push_back(0x0035); // TLS_RSA_WITH_AES_256_CBC_SHA
   std::sort(cipher_suites.begin(), cipher_suites.end());
   return cipher_suites;
 }
```

**Comment by uazo** [comment]
therefore, it appears that, the hw aes capable is described by bit 25 of the eax cpuid (ref https://en.wikipedia.org/wiki/CPUID).
According to wikipedia https://en.wikipedia.org/wiki/AES_instruction_set for example the i3 do not have aes support and therefore have a different and recognizable payload, I will check, I have available an i3.

arm cpus with aes support are also indicated (ref https://developer.arm.com/documentation/ddi0487/latest), but, for me, it is difficult to understand because I don't know them. trying with various devices in browserstack, I never detected any differences.

in conclusion, if, for v111, in JA3n Hash the string `aa56c057ad164ec4fdcb7a5a283be9fc` is not presented
the device is recognizable at network stack because it seems to be different from chrome.

I am mostly inclined to leave it that way and try to force the order of the list of encryption algorithms.
unfortunately, the problem here is that I cannot directly edit boringssl with the patch system I use (same thing that happened with skia)

**Comment by uazo** [comment]
you don't have to worry, it is simply because it doesn't add anything technical to the issue. 
I'm happy to answer any questions, go ahead.

**Comment by uazo** [comment]
>  I will check, I have available an i3.

checked, the i3 supports aes extension, maybe the page on wikipedia is wrong. i will try with a virtual machine.

**Comment by uazo** [comment]
I tried to force the order with `SSL_set_strict_cipher_list()` but it does not seem to be respected by the ech.
I have opened a bug in boringssl so we know what they think: https://bugs.chromium.org/p/boringssl/issues/detail?id=579

**Comment by uazo** [comment]
already received the answer.
if I understand correctly, basically the google team is saying that it is more risky to use aes via software than to have an extra bit of tracking.
I am not a security expert, but I think I will open a new issue for a user alert if own device is more easily traceable in case it does not have hardware aes support.
regarding the point at hand, the next step is to see if, by using a weak cipher, chromium alerts the user.

**Comment by uazo** [comment]
> by using a weak cipher, chromium alerts the user.

verified, yes, chromium does not allow connection with error  `ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY`

**Comment by uazo** [comment]
Relative to the request, therefore, no change is necessary

**Comment by uazo** [comment]
only as an additional note, edge, chrome and brave instead **allow access**
firefox blocks it

**Comment by ghost** [comment]
Not sure if it is of help, but weak ciphers for Chrome (and Cromite of course) on Windows can be disabled via shortcut flags. The following disables weak ciphers and keeps only non-CBC TLS 1.2 and 1.3 ciphers with PFS   "--cipher-suite-blacklist=0xc013,0xc014,0x009c,0x009d,0x002f,0x0035" .

Maybe move this to the official Cromite repository?

**Comment by uazo** [comment]
@GY8VSdYYzvL8-K6T 
https://github.com/uazo/bromite-buildtools/issues/73#issuecomment-1481091171 this no longer works?
should the browser warn the user or does it not?
