### ISSUE TITLE
Bromite Official vs these buids - performance difference?

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [uazo/bromite-buildtools#75]
Official Bromite feels much snapper compared to builds I find here. Sometimes pages just stall, not respond. For example, speedtest.net quickly reports latency (about 40ms), then stalls for good 5-10 seconds until speed test starts and download results are in 50-80Mb range. The numbers look good, but the stalling ruins the exerpience. What causes it? I use the same tweaks for Bromite offifcial and Uazo's build. Maybe its the new adblockers that do that?

**Comment by welkinpc-91** [comment]
Have you added some filter lists? Possibily with uBlock syntax? (I've found out the hard way the adblock does not play nice woth uBlocks lists.)

The builds on my stock os samsung run exactly like Bromite, but I have added my own custom filters lists. (with Adblock Plus syntax).

Aside turning on Easylist Cookies and Italian, I've had few crashes changing some settings (timezone changes and the new adblock settings sometimes), but browsing the web, exporting and re-importing bookmarks has been the same.

**Comment by n-buna404** [comment]
well another reason may be uazo test build only offer arm64 version 
so for kinda older hardware and smaller ram phone. It would not feel as snappy

**Comment by uazo** [comment]
> Sometimes pages just stall, not respond. 

if this happens to you, try going back to the android recents and then to the application. if so, it happened [some time ago](https://github.com/bromite/bromite/issues/1837).

>  then stalls for good 5-10 seconds until speed test starts and download results are in 50-80Mb range

too vague as an indication.
my advice is to try again with javascript JIT activated or with another network.

> The numbers look good, but the stalling ruins the exerpience. What causes it? I use the same tweaks for Bromite offifcial and Uazo's build. Maybe its the new adblockers that do that?

unfortunately, the two versions are not directly comparable, one being at v108 and the other at v110.

**Comment by GY8VSdYYzvL8-K6T** [comment]
I figured it out. It wasn't related to Bromite or your work.
