### ISSUE TITLE
Suggestion For Future.

### ISSUE THREAD

**Issue by blogmangit** [uazo/bromite-buildtools#76]
Please give a name to this project like say "Bromium" brotherhood chromium and launch it full phase because I personally don't think bromite will be continued. Yours is the last option remaining. Also choose a nice logo with adaptive icon.

Thank to you.

**Comment by uazo** [comment]
I am not worried about that for now

**Comment by ViktorKahu** [comment]
Perhaps the time has come to reopen this ticket....?
