### ISSUE TITLE
Bitwarden does not work with your version of Bromite.

### ISSUE THREAD

**Issue by ViktorKahu** [uazo/bromite-buildtools#77]
When I try to auto fill the login and password details with Bitwarden on any site, it says: "There are no stored elements for org.bromite.dev".

No such problems evident with official Bromite, Vanadium or Brave.

Would be nice if someone can fix it.

**Comment by ViktorKahu** [comment]
No.

I am not a developer by any means, but I think I can point you to where the problem lies...

While the Bitwarden app should be looking for the url of the login screen of any website in question (for example login.github.com), it instead thinks that I am trying to log in to an android application package (org.bromite.dev).

I have no idea why that is, possibly has something to do with the name of the package...

Bitwarden can under normal circumstances log into websites through the browser or log onto android apps (for example tutanota). For some reason it is confusing these 2 principles.

Like I said, I think it's this app because everything works with other apps as stated in comments above. Infact, with years of use, this app is the only time this ever happened.

Aprreciate your help.

**Comment by ViktorKahu** [comment]
...Also, Official bromite has a setting that is missing in your version completely.

Under site settings: "offer to login using third parties...something".

May be it has something to do with that?

**Comment by welkinpc-91** [comment]
If this is any additional info to Uazo, I've tried to get autofill working using KeepassDX (even though for Github I use the app)

Picks up the saved info (url, account, password, 2FA) without any trouble.
Seems a problem specific to Bitwarden. (Haven't tried other forks of Keepass to be 100% sure, as far as I know keepass2android required a plugin to even autofill in the first place.)

**Comment by ViktorKahu** [comment]
> Even though, I don't use this functionality, @uazo and @ViktorKahu may i suggest you something, if you reply me.

Sure, that's why we are here, to explore ideas and find solutions.

**Comment by ViktorKahu** [comment]
> If this is any additional info to Uazo, I've tried to get autofill working using KeepassDX (even though for Github I use the app)
> 
> Picks up the saved info (url, account, password, 2FA) without any trouble. Seems a problem specific to Bitwarden, offline password manager work I guess? (Haven't tried other forks of Keepass to be 100% sure, as far as I know keepass2android required a plugin to even autofill in the first place.)

I use the bitwarden app. I never use the keyboard function. So everything I described above is to be presumed I'm using the app (if it matters).

So the popup does come up offering to fill the login details, but when I click on it, what I described above happens.

**Comment by welkinpc-91** [comment]
> I use the bitwarden app. I never use the keyboard function. So everything I described above is to be presumed I'm using the app (if it matters).
> 
> So the popup does come up offering to fill the login details, but when I click on it, what I described above happens.

I already assumed so already.
I just pointed out that the one I use (offline or not it's also an app) can autofill on this beta without an hitch. (KeePassDX has both a special keyboard and the standard autofill like Bitwarden does, and I tested the latter to put myself in your shoes)

We would need someone using another online password manager to point if the problem is just Bitwarden's autofill.

**Comment by ViktorKahu** [comment]
> > I use the bitwarden app. I never use the keyboard function. So everything I described above is to be presumed I'm using the app (if it matters).
> > So the popup does come up offering to fill the login details, but when I click on it, what I described above happens.
> 
> I already assumed so already. I just pointed out that the one I use (offline or not it's also an app) can autofill on this beta without an hitch. (KeePassDX has both a special keyboard and the standard autofill like Bitwarden does, and I tested the latter to put myself in your shoes)
> 
> We would need someone using another online password manager to point if the problem is just Bitwarden's autofill.

Sure, I see what you are saying, makes sense.

But in an attempt not to irreleventalize this issue, I think we should also accept the fact that "Bromium" does something different to official Bromite/Vanadium/Brave to cause this behavior (with a specific app if you like) - that was tested and confirmed.

If Uazo was to say that it's a problem with Bitwarden and close this issue as "not planned", I would respect that. But he is a developer and I'm not, he may know something that I don't and he may know where to look...

**Comment by uazo** [comment]
there is no difference in functionality between bromite and this repo (I made that patch :)
what comes to mind is the different package name: perhaps bitwarden applies a filter on the sender to inhibit access to applications that are not detected as browsers.

in any case, for now, it is a non-issue: it can be checked when the 111 version of bromite is released.

**Comment by tankaras** [comment]
This is the problem with Bitwarden
https://github.com/fork-maintainers/iceraven-browser/issues/210#issuecomment-705859502

Any browser that's not whitelisted with them will not work with BW
https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs#L55

@uazo Would have to make this project official and submit a request to BW for whitelist. Or as a hack change the app id to bromite's which is already whitelisted but conflicts with original bromite.

**Comment by ViktorKahu** [comment]
> there is no difference in functionality between bromite and this repo (I made that patch :) what comes to mind is the different package name: perhaps bitwarden applies a filter on the sender to inhibit access to applications that are not detected as browsers.
> 
> in any case, for now, it is a non-issue: it can be checked when the 111 version of bromite is released.

I sincerely hope that you know something I dont. Because if we are only assuming that any new version of Bromite will be released, I think we are kidding ourselves. With every day that passes, that hope fades away a little more. I don't even hope that I'm wrong anymore, I've accepted the inevitable.

**Comment by ViktorKahu** [comment]
> If this is any additional info to Uazo, I've tried to get autofill working using KeepassDX (even though for Github I use the app)
> 
> Picks up the saved info (url, account, password, 2FA) without any trouble. Seems a problem specific to Bitwarden, offline password manager work I guess? (Haven't tried other forks of Keepass to be 100% sure, as far as I know keepass2android required a plugin to even autofill in the first place.)

I have now migrated to KeepassDX and have no more issues. Moreover, I find it's functionality and features better than Bitwarden. Thanks for the tip.

**Comment by coxackie** [comment]
@uazo would you maybe consider changing the app I'd from org.bromite.bromite.dev to org.bromite.bromite? Or maybe to org.chromium.chrome? The last one is allowed in bitwarden, and would make you feel less uneasy, probably.

**Comment by uazo** [comment]
no, there is work to be done before that.
all blocked until I understand how I want to proceed with this fork.

**Comment by coxackie** [comment]
ok, fair enough. I understand this may be a difficult step, so if you would like the community's feedback, you can open a discussion. We all need this project to continue, whether it is under a different name or not, it has to go on...

**Comment by uazo** [comment]
checked, I assume it is a bitwarden bug.
browser side I do not detect any problems

**Comment by uazo** [comment]
> would you maybe consider changing the app ID

no, not for now.
the idea is to change this browser into `cromite`

**Comment by uazo** [comment]
> Any browser that's not whitelisted with them will not work with BW

this browser uses android's native autofill, so I don't think that change is necessary

**Comment by uazo** [comment]
no, please wait.
i am about to bring out 'chromite', the request had better be made under that name

**Comment by coxackie** [comment]
Is chromite really coming out soon? Because this bitwarden issue is really annoying.

**Comment by uazo** [comment]
Yes, that is the intention.

NOTE: cromite (without h) and with the phonetics in Italian [kroˈmite](https://translate.google.com/translate_tts?q=cromite&ie=UTF-8&tl=it&client=tw-ob) :)

**Comment by BabyOilJohnson** [comment]
So is this issue be fixed in cromite?

**Comment by coxackie** [comment]
No, it will not, bitwarden will still have to whitelist the new browser. So, it could take quite some time. @uazo maybe you can help with pushing bitwarden, since you will be the author of the browser? (Still waiting, btw...)

**Comment by uazo** [comment]
pushing maybe not suitable.
if I were them, I would wait to see if it becomes widespread, so I think it's going to be a long process.
sorry.
meanwhile the browser has to come out first.

**Comment by coxackie** [comment]
@uazo yes, the browser has to come out first... we are all waiting... any updates?

**Comment by hj-collab** [comment]
@uazo They have closed my request. I guess you can make the request when you release Cromite. Will the windows binaries be digitally signed with your certificate in future?

**Comment by uazo** [comment]
>  Will the windows binaries be digitally signed with your certificate in future?

yes, as soon as I find someone who sells code sign certificates at a reasonable price, if you know of any...

**Comment by avipars** [comment]
https://community.bitwarden.com/t/allow-users-to-add-new-browser-to-the-autofill-whitelist/59706
