### ISSUE TITLE
Webgl fingerprint hash not randomized

### ISSUE THREAD

**Issue by ViktorKahu** [uazo/bromite-buildtools#86]
As the title says.

Tried reopening app/restarting phone - always the same webgl hash result.

It is noteworthy to mention that surprisingly, the webgl hash gets randomized by even Samsung Browser.

Tested with coveryourtracks.org

**Comment by uazo** [comment]
is correct, we do not always make the value random.
For example, for webgl you should have bf6b0994b43968f4b930a907d7a0d31e (in coveryourtracks.org) which is the same value for everyone.
if you know of devices with different values (or of the ineffectiveness of this approach) please give us more information.

**Comment by ViktorKahu** [comment]
My bad, I mistakenly thought that value was unique to my phone. Learned something new.

Thanks a lot for explaining.

**Comment by uazo** [comment]
> Learned something new.

Don't worry: faking it is easy, faking it well is not at all!

> Thanks a lot for explaining.

no problem at all! in fact, such messages are welcome, as I have no telemetry of any kind only a field verification assures me that it works.
