### ISSUE TITLE
Github acting strange with latest patch.

### ISSUE THREAD

**Issue by welkinpc-91** [uazo/bromite-buildtools#90]
Github pages aren't loading aside the initial load. (can load into a repo just fine, trying to go to issues/discussion/etc. will not load, browser doesn't crash but I'm stuck into a project main page)

Didn't happen with the previous one (both versions are v111.0.5563.65), can't reproduce on Bromite (with the same site settings and adblock.dat), Brave or Mull. 
Github behaves as normal.

Haven't changed any setting in the test adblock either between the two patches.
Also haven't experienced any weird behaviours into other sites I visit.

Other info is stock Android 11 on a Samsung.

Is it just me? Or is it behaving differently for someone else?

**Comment by uazo** [comment]
thanks for the tip.

> Is it just me? 

I do not detect any problems.
theoretically among those releases, there is nothing that could generate that error, which I assume is on the network stack.
if you are able, you could send the trace files extracted from `chrome://net-export/` (see 
https://www.chromium.org/for-testers/providing-network-details).
you should also check what is happening via developer tools: with a desktop and the device connected via usb navigate to `chrome://inspect/#devices`.

**Comment by welkinpc-91** [comment]
I managed to fix the issue before I could even try to plug my phone to a computer.
Unsure if this is relevant or not, apparently my site settings glitched out or something in the update of the app.

To clarify: I compartmentalize my browsing in android with multiple browsers, leaving private or log-in less browsing to Bromite and Mull (and since Bromite has yet to be update, this beta)

As such I block cookies with Bromite and the Beta, leaving site exceptions for sites thar break.
For some weird reason (I'm not a programmer so I don't really understand), the exceptions didn't work anymore.

By removing and adding them back I've got  Github to work properly again, so it must have been site breakage by cookie denial.
Strange they still appeared intact only to not be the case.

Another setting that glitched out is the userscript, they still work, but the graphical part is messed up, when you try to remove them they do stop working as intended but they still appear in the settings page and still on, even though they clearly no longer work and are present, I'm still able to load them and get them to work properly, the UI is just frozen. Unsure if this happens only to me or if this is a bug.

Sorry for the trouble.

**Comment by HarriBuh** [comment]
I'm having the exact same issue and since I did not understand what @welkinpc-91 did, I haven't been able to fix it yet.
I'm now trying to gather the log file just as @uazo suggested.

**Comment by welkinpc-91** [comment]
> I'm having the exact same issue and since I did not understand what @welkinpc-91 did, I haven't been able to fix it yet.
> I'm now trying to gather the log file just as @uazo suggested.

I deleted the site exception of github.com in cookies (they're set to block all since I don't log-in using Bromite or the test version), then added it back in, and it fixed it. (Done with the rest of exception for safety)

For the userscript settings they're still glitched out.

**Comment by uazo** [comment]
> For the userscript settings they're still glitched out.

you are right, I did not realise this
opened https://github.com/uazo/bromite-buildtools/issues/91

**Comment by welkinpc-91** [comment]
At least on my end, everything is fixed now!

**Comment by HarriBuh** [comment]
Same here 🙌
